[package]
name = "jacquard-lexicon"
description = "Lexicon schema parsing and code generation for Jacquard"
edition.workspace = true
version = "0.9.2"
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
exclude.workspace = true
license.workspace = true

[features]
default = ["codegen"]
codegen = ["dep:prettyplease", "dep:syn", "dep:quote", "dep:proc-macro2", "dep:heck"]

[dependencies]
cid.workspace = true
dashmap.workspace = true
heck = { workspace = true, optional = true }
inventory = "0.3"
jacquard-common = { version = "0.9", path = "../jacquard-common" }
miette = { workspace = true }
multihash.workspace = true
prettyplease = { workspace = true, optional = true }
proc-macro2 = { workspace = true, optional = true }
quote = { workspace = true, optional = true }
serde.workspace = true
serde_ipld_dagcbor.workspace = true
serde_json.workspace = true
serde_repr.workspace = true
serde_with.workspace = true
sha2.workspace = true
syn = { workspace = true, optional = true }
thiserror.workspace = true
unicode-segmentation = "1.12"

[dev-dependencies]
bytes = { workspace = true }
jacquard-derive = { version = "0.9", path = "../jacquard-derive"}
tempfile = { version = "3.23.0" }
