[package]
name = "jacquard-lexicon"
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
documentation.workspace = true
exclude.workspace = true
description.workspace = true

[[bin]]
name = "jacquard-codegen"
path = "src/bin/codegen.rs"

[dependencies]
clap = { workspace = true }
heck = "0.5.0"
itertools = "0.14.0"
jacquard-common = { version = "0.1.0", path = "../jacquard-common" }
miette = "7.6.0"
prettyplease = "0.2.37"
proc-macro2 = "1.0.101"
quote = "1.0.41"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serde_repr = "0.1.20"
serde_with = "3.14.1"
syn = "2.0.106"
thiserror = "2.0.17"
