[package]
name = "jacquard-api"
description = "Generated AT Protocol API bindings for Jacquard"
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
exclude.workspace = true
license.workspace = true

[package.metadata.docs.rs]
features = [ "com_atproto", "app_bsky", "chat_bsky", "tools_ozone" ]

[features]
default = [ "com_atproto"]
app_bsky = []
chat_bsky = []
com_atproto = []
tools_ozone = []

[dependencies]
bon = "3"
bytes = { workspace = true, features = ["serde"] }
jacquard-common = { version = "0.2.0", path = "../jacquard-common" }
jacquard-derive = { version = "0.2.0", path = "../jacquard-derive" }
miette.workspace = true
serde.workspace = true
thiserror.workspace = true
