[package]
name = "jacquard-api"
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
documentation.workspace = true
exclude.workspace = true
description.workspace = true

[features]
default = ["app_bsky", "com_atproto", "tools_ozone", "chat_bsky"]
app_bsky = []
chat_bsky = []
com_atproto = []
tools_ozone = []

[dependencies]
bon = "3"
bytes = { version = "1.10.1", features = ["serde"] }
jacquard-common = { version = "0.1.0", path = "../jacquard-common" }
jacquard-derive = { version = "0.1.0", path = "../jacquard-derive" }
miette = "7.6.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
