[package]
name = "jacquard-api"
description = "Generated AT Protocol API bindings for Jacquard"
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
documentation = "https://docs.rs/jacquard-api"
exclude.workspace = true

[features]
default = [ "com_atproto"]
app_bsky = []
chat_bsky = []
com_atproto = []
tools_ozone = []

[dependencies]
bon = "3"
bytes = { workspace = true, features = ["serde"] }
jacquard-common = { path = "../jacquard-common" }
jacquard-derive = { path = "../jacquard-derive" }
miette.workspace = true
serde.workspace = true
thiserror.workspace = true
