// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: tools.ozone.queue.routeReports
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};
use jacquard_derive::{IntoStatic, open_union};
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct RouteReports<S: BosStr = DefaultStr> {
    ///End of report ID range (inclusive). Difference between start and end must be less than 5,000.
    pub end_report_id: i64,
    ///Start of report ID range (inclusive).
    pub start_report_id: i64,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct RouteReportsOutput<S: BosStr = DefaultStr> {
    ///The number of reports assigned to a queue.
    pub assigned: i64,
    ///The number of reports with no matching queue.
    pub unmatched: i64,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

#[derive(
    Serialize, Deserialize, Debug, Clone, PartialEq, Eq, thiserror::Error, miette::Diagnostic,
)]
#[serde(tag = "error", content = "message")]
pub enum RouteReportsError {
    /// The request is invalid, such as missing required fields or invalid field values.
    #[serde(rename = "OutOfRange")]
    OutOfRange(Option<SmolStr>),
    /// Catch-all for unknown error codes.
    #[serde(untagged)]
    Other {
        error: SmolStr,
        message: Option<SmolStr>,
    },
}

impl core::fmt::Display for RouteReportsError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::OutOfRange(msg) => {
                write!(f, "OutOfRange")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Other { error, message } => {
                write!(f, "{}", error)?;
                if let Some(msg) = message {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
        }
    }
}

/// Response type for tools.ozone.queue.routeReports
pub struct RouteReportsResponse;
impl jacquard_common::xrpc::XrpcResp for RouteReportsResponse {
    const NSID: &'static str = "tools.ozone.queue.routeReports";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = RouteReportsOutput<S>;
    type Err = RouteReportsError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for RouteReports<S> {
    const NSID: &'static str = "tools.ozone.queue.routeReports";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Response = RouteReportsResponse;
}

/// Endpoint type for tools.ozone.queue.routeReports
pub struct RouteReportsRequest;
impl jacquard_common::xrpc::XrpcEndpoint for RouteReportsRequest {
    const PATH: &'static str = "/xrpc/tools.ozone.queue.routeReports";
    const METHOD: jacquard_common::xrpc::XrpcMethod =
        jacquard_common::xrpc::XrpcMethod::Procedure("application/json");
    type Request<S: BosStr> = RouteReports<S>;
    type Response = RouteReportsResponse;
}

pub mod route_reports_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type EndReportId;
        type StartReportId;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type EndReportId = Unset;
        type StartReportId = Unset;
    }
    ///State transition - sets the `end_report_id` field to Set
    pub struct SetEndReportId<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetEndReportId<St> {}
    impl<St: State> State for SetEndReportId<St> {
        type EndReportId = Set<members::end_report_id>;
        type StartReportId = St::StartReportId;
    }
    ///State transition - sets the `start_report_id` field to Set
    pub struct SetStartReportId<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetStartReportId<St> {}
    impl<St: State> State for SetStartReportId<St> {
        type EndReportId = St::EndReportId;
        type StartReportId = Set<members::start_report_id>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `end_report_id` field
        pub struct end_report_id(());
        ///Marker type for the `start_report_id` field
        pub struct start_report_id(());
    }
}

/// Builder for constructing an instance of this type.
pub struct RouteReportsBuilder<St: route_reports_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<i64>, Option<i64>),
    _type: PhantomData<fn() -> S>,
}

impl RouteReports<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> RouteReportsBuilder<route_reports_state::Empty, DefaultStr> {
        RouteReportsBuilder::new()
    }
}

impl<S: BosStr> RouteReports<S> {
    /// Create a new builder for this type
    pub fn builder() -> RouteReportsBuilder<route_reports_state::Empty, S> {
        RouteReportsBuilder::builder()
    }
}

impl RouteReportsBuilder<route_reports_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        RouteReportsBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> RouteReportsBuilder<route_reports_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        RouteReportsBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> RouteReportsBuilder<St, S>
where
    St: route_reports_state::State,
    St::EndReportId: route_reports_state::IsUnset,
{
    /// Set the `endReportId` field (required)
    pub fn end_report_id(
        mut self,
        value: impl Into<i64>,
    ) -> RouteReportsBuilder<route_reports_state::SetEndReportId<St>, S> {
        self._fields.0 = Option::Some(value.into());
        RouteReportsBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> RouteReportsBuilder<St, S>
where
    St: route_reports_state::State,
    St::StartReportId: route_reports_state::IsUnset,
{
    /// Set the `startReportId` field (required)
    pub fn start_report_id(
        mut self,
        value: impl Into<i64>,
    ) -> RouteReportsBuilder<route_reports_state::SetStartReportId<St>, S> {
        self._fields.1 = Option::Some(value.into());
        RouteReportsBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> RouteReportsBuilder<St, S>
where
    St: route_reports_state::State,
    St::EndReportId: route_reports_state::IsSet,
    St::StartReportId: route_reports_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> RouteReports<S> {
        RouteReports {
            end_report_id: self._fields.0.unwrap(),
            start_report_id: self._fields.1.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> RouteReports<S> {
        RouteReports {
            end_report_id: self._fields.0.unwrap(),
            start_report_id: self._fields.1.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}
