// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: fyi.questionable.richtext.content
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{Bos, DefaultStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
use crate::fyi_questionable::richtext::blockquote::Blockquote;
use crate::fyi_questionable::richtext::bsky_post::BskyPost;
use crate::fyi_questionable::richtext::code::Code;
use crate::fyi_questionable::richtext::header::Header;
use crate::fyi_questionable::richtext::horizontal_rule::HorizontalRule;
use crate::fyi_questionable::richtext::image::Image;
use crate::fyi_questionable::richtext::list::List;
use crate::fyi_questionable::richtext::math::Math;
use crate::fyi_questionable::richtext::text::Text;
use crate::fyi_questionable::richtext::website::Website;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(
        serialize = "S: Serialize + Bos<str> + AsRef<str>",
        deserialize = "S: Deserialize<'de> + Bos<str> + AsRef<str>"
    )
)]
pub struct Content<S: Bos<str> + AsRef<str> = DefaultStr> {
    ///Array of content blocks
    pub items: Vec<ContentItemsItem<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[open_union]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    tag = "$type",
    bound(
        serialize = "S: Serialize + Bos<str> + AsRef<str>",
        deserialize = "S: Deserialize<'de> + Bos<str> + AsRef<str>"
    )
)]
pub enum ContentItemsItem<S: Bos<str> + AsRef<str> = DefaultStr> {
    #[serde(rename = "fyi.questionable.richtext.text")]
    Text(Box<Text<S>>),
    #[serde(rename = "fyi.questionable.richtext.blockquote")]
    Blockquote(Box<Blockquote<S>>),
    #[serde(rename = "fyi.questionable.richtext.bskyPost")]
    BskyPost(Box<BskyPost<S>>),
    #[serde(rename = "fyi.questionable.richtext.code")]
    Code(Box<Code<S>>),
    #[serde(rename = "fyi.questionable.richtext.header")]
    Header(Box<Header<S>>),
    #[serde(rename = "fyi.questionable.richtext.horizontalRule")]
    HorizontalRule(Box<HorizontalRule<S>>),
    #[serde(rename = "fyi.questionable.richtext.image")]
    Image(Box<Image<S>>),
    #[serde(rename = "fyi.questionable.richtext.math")]
    Math(Box<Math<S>>),
    #[serde(rename = "fyi.questionable.richtext.list")]
    List(Box<List<S>>),
    #[serde(rename = "fyi.questionable.richtext.website")]
    Website(Box<Website<S>>),
}

impl<S: Bos<str> + AsRef<str>> LexiconSchema for Content<S> {
    fn nsid() -> &'static str {
        "fyi.questionable.richtext.content"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_fyi_questionable_richtext_content()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.items;
            #[allow(unused_comparisons)]
            if value.len() > 1000usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("items"),
                    max: 1000usize,
                    actual: value.len(),
                });
            }
        }
        Ok(())
    }
}

pub mod content_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Items;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Items = Unset;
    }
    ///State transition - sets the `items` field to Set
    pub struct SetItems<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetItems<S> {}
    impl<S: State> State for SetItems<S> {
        type Items = Set<members::items>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `items` field
        pub struct items(());
    }
}

/// Builder for constructing an instance of this type
pub struct ContentBuilder<'a, S: content_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<Vec<ContentItemsItem<S>>>,),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> Content<'a> {
    /// Create a new builder for this type
    pub fn new() -> ContentBuilder<'a, content_state::Empty> {
        ContentBuilder::new()
    }
}

impl<'a> ContentBuilder<'a, content_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        ContentBuilder {
            _state: PhantomData,
            _fields: (None,),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> ContentBuilder<'a, S>
where
    S: content_state::State,
    S::Items: content_state::IsUnset,
{
    /// Set the `items` field (required)
    pub fn items(
        mut self,
        value: impl Into<Vec<ContentItemsItem<S>>>,
    ) -> ContentBuilder<'a, content_state::SetItems<S>> {
        self._fields.0 = Option::Some(value.into());
        ContentBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> ContentBuilder<'a, S>
where
    S: content_state::State,
    S::Items: content_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> Content<'a> {
        Content {
            items: self._fields.0.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<SmolStr, Data<'a>>,
    ) -> Content<'a> {
        Content {
            items: self._fields.0.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_fyi_questionable_richtext_content() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("fyi.questionable.richtext.content"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Object(LexObject {
                    required: Some(vec![SmolStr::new_static("items")]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("items"),
                            LexObjectProperty::Array(LexArray {
                                description: Some(
                                    CowStr::new_static("Array of content blocks"),
                                ),
                                items: LexArrayItem::Union(LexRefUnion {
                                    refs: vec![
                                        CowStr::new_static("fyi.questionable.richtext.text"),
                                        CowStr::new_static("fyi.questionable.richtext.blockquote"),
                                        CowStr::new_static("fyi.questionable.richtext.bskyPost"),
                                        CowStr::new_static("fyi.questionable.richtext.code"),
                                        CowStr::new_static("fyi.questionable.richtext.header"),
                                        CowStr::new_static("fyi.questionable.richtext.horizontalRule"),
                                        CowStr::new_static("fyi.questionable.richtext.image"),
                                        CowStr::new_static("fyi.questionable.richtext.math"),
                                        CowStr::new_static("fyi.questionable.richtext.text"),
                                        CowStr::new_static("fyi.questionable.richtext.list"),
                                        CowStr::new_static("fyi.questionable.richtext.website")
                                    ],
                                    closed: Some(false),
                                    ..Default::default()
                                }),
                                max_length: Some(1000usize),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}