// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.beaconbits.favorites
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{Did, AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
/// A list of favorited user DIDs (legacy singleton record).

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "app.beaconbits.favorites",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Favorites<S: BosStr = DefaultStr> {
    ///List of favorited user DIDs
    pub dids: Vec<Did<S>>,
    ///Timestamp when the favorites list was last updated
    pub updated_at: Datetime,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct FavoritesGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: Favorites<S>,
}

impl<S: BosStr> Favorites<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, FavoritesRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct FavoritesRecord;
impl XrpcResp for FavoritesRecord {
    const NSID: &'static str = "app.beaconbits.favorites";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = FavoritesGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<FavoritesGetRecordOutput<S>> for Favorites<S> {
    fn from(output: FavoritesGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Favorites<S> {
    const NSID: &'static str = "app.beaconbits.favorites";
    type Record = FavoritesRecord;
}

impl Collection for FavoritesRecord {
    const NSID: &'static str = "app.beaconbits.favorites";
    type Record = FavoritesRecord;
}

impl<S: BosStr> LexiconSchema for Favorites<S> {
    fn nsid() -> &'static str {
        "app.beaconbits.favorites"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_app_beaconbits_favorites()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.dids;
            #[allow(unused_comparisons)]
            if value.len() > 500usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("dids"),
                    max: 500usize,
                    actual: value.len(),
                });
            }
        }
        Ok(())
    }
}

pub mod favorites_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Dids;
        type UpdatedAt;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Dids = Unset;
        type UpdatedAt = Unset;
    }
    ///State transition - sets the `dids` field to Set
    pub struct SetDids<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetDids<St> {}
    impl<St: State> State for SetDids<St> {
        type Dids = Set<members::dids>;
        type UpdatedAt = St::UpdatedAt;
    }
    ///State transition - sets the `updated_at` field to Set
    pub struct SetUpdatedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetUpdatedAt<St> {}
    impl<St: State> State for SetUpdatedAt<St> {
        type Dids = St::Dids;
        type UpdatedAt = Set<members::updated_at>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `dids` field
        pub struct dids(());
        ///Marker type for the `updated_at` field
        pub struct updated_at(());
    }
}

/// Builder for constructing an instance of this type.
pub struct FavoritesBuilder<St: favorites_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<Vec<Did<S>>>, Option<Datetime>),
    _type: PhantomData<fn() -> S>,
}

impl Favorites<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> FavoritesBuilder<favorites_state::Empty, DefaultStr> {
        FavoritesBuilder::new()
    }
}

impl<S: BosStr> Favorites<S> {
    /// Create a new builder for this type
    pub fn builder() -> FavoritesBuilder<favorites_state::Empty, S> {
        FavoritesBuilder::builder()
    }
}

impl FavoritesBuilder<favorites_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        FavoritesBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> FavoritesBuilder<favorites_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        FavoritesBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> FavoritesBuilder<St, S>
where
    St: favorites_state::State,
    St::Dids: favorites_state::IsUnset,
{
    /// Set the `dids` field (required)
    pub fn dids(
        mut self,
        value: impl Into<Vec<Did<S>>>,
    ) -> FavoritesBuilder<favorites_state::SetDids<St>, S> {
        self._fields.0 = Option::Some(value.into());
        FavoritesBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> FavoritesBuilder<St, S>
where
    St: favorites_state::State,
    St::UpdatedAt: favorites_state::IsUnset,
{
    /// Set the `updatedAt` field (required)
    pub fn updated_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> FavoritesBuilder<favorites_state::SetUpdatedAt<St>, S> {
        self._fields.1 = Option::Some(value.into());
        FavoritesBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> FavoritesBuilder<St, S>
where
    St: favorites_state::State,
    St::Dids: favorites_state::IsSet,
    St::UpdatedAt: favorites_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Favorites<S> {
        Favorites {
            dids: self._fields.0.unwrap(),
            updated_at: self._fields.1.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<SmolStr, Data<S>>,
    ) -> Favorites<S> {
        Favorites {
            dids: self._fields.0.unwrap(),
            updated_at: self._fields.1.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_app_beaconbits_favorites() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("app.beaconbits.favorites"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "A list of favorited user DIDs (legacy singleton record).",
                        ),
                    ),
                    key: Some(CowStr::new_static("literal:self")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("dids"),
                                SmolStr::new_static("updatedAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("dids"),
                                LexObjectProperty::Array(LexArray {
                                    description: Some(
                                        CowStr::new_static("List of favorited user DIDs"),
                                    ),
                                    items: LexArrayItem::String(LexString {
                                        format: Some(LexStringFormat::Did),
                                        ..Default::default()
                                    }),
                                    max_length: Some(500usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("updatedAt"),
                                LexObjectProperty::String(LexString {
                                    description: Some(
                                        CowStr::new_static(
                                            "Timestamp when the favorites list was last updated",
                                        ),
                                    ),
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}