// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.bsky.contact.dismissMatch
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, Bos, DefaultStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::Did;
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
#[serde(
    bound(
        serialize = "S: Serialize + Bos<str> + AsRef<str>",
        deserialize = "S: Deserialize<'de> + Bos<str> + AsRef<str>"
    )
)]
pub struct DismissMatch<S: Bos<str> + AsRef<str> = DefaultStr> {
    ///The subject's DID to dismiss the match with.
    pub subject: Did<S>,
    #[serde(flatten)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase")]
#[serde(
    bound(
        serialize = "S: Serialize + Bos<str> + AsRef<str>",
        deserialize = "S: Deserialize<'de> + Bos<str> + AsRef<str>"
    )
)]
pub struct DismissMatchOutput<S: Bos<str> + AsRef<str> = DefaultStr> {
    #[serde(flatten)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic
)]

#[serde(tag = "error", content = "message")]
pub enum DismissMatchError {
    #[serde(rename = "InvalidDid")]
    InvalidDid(Option<SmolStr>),
    #[serde(rename = "InternalError")]
    InternalError(Option<SmolStr>),
    /// Catch-all for unknown error codes.
    #[serde(untagged)]
    Other { error: SmolStr, message: Option<SmolStr> },
}

impl core::fmt::Display for DismissMatchError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::InvalidDid(msg) => {
                write!(f, "InvalidDid")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::InternalError(msg) => {
                write!(f, "InternalError")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Other { error, message } => {
                write!(f, "{}", error)?;
                if let Some(msg) = message {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
        }
    }
}

/// Response type for app.bsky.contact.dismissMatch
pub struct DismissMatchResponse;
impl jacquard_common::xrpc::XrpcResp for DismissMatchResponse {
    const NSID: &'static str = "app.bsky.contact.dismissMatch";
    const ENCODING: &'static str = "application/json";
    type Output<S: Bos<str> + AsRef<str>> = DismissMatchOutput<S>;
    type Err = DismissMatchError;
}

impl<S: Bos<str> + AsRef<str> + Serialize> jacquard_common::xrpc::XrpcRequest
for DismissMatch<S> {
    const NSID: &'static str = "app.bsky.contact.dismissMatch";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = DismissMatchResponse;
}

/// Endpoint type for app.bsky.contact.dismissMatch
pub struct DismissMatchRequest;
impl jacquard_common::xrpc::XrpcEndpoint for DismissMatchRequest {
    const PATH: &'static str = "/xrpc/app.bsky.contact.dismissMatch";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<S: Bos<str> + AsRef<str>> = DismissMatch<S>;
    type Response = DismissMatchResponse;
}

pub mod dismiss_match_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Subject;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Subject = Unset;
    }
    ///State transition - sets the `subject` field to Set
    pub struct SetSubject<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetSubject<S> {}
    impl<S: State> State for SetSubject<S> {
        type Subject = Set<members::subject>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `subject` field
        pub struct subject(());
    }
}

/// Builder for constructing an instance of this type
pub struct DismissMatchBuilder<'a, S: dismiss_match_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<Did<S>>,),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> DismissMatch<'a> {
    /// Create a new builder for this type
    pub fn new() -> DismissMatchBuilder<'a, dismiss_match_state::Empty> {
        DismissMatchBuilder::new()
    }
}

impl<'a> DismissMatchBuilder<'a, dismiss_match_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        DismissMatchBuilder {
            _state: PhantomData,
            _fields: (None,),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> DismissMatchBuilder<'a, S>
where
    S: dismiss_match_state::State,
    S::Subject: dismiss_match_state::IsUnset,
{
    /// Set the `subject` field (required)
    pub fn subject(
        mut self,
        value: impl Into<Did<S>>,
    ) -> DismissMatchBuilder<'a, dismiss_match_state::SetSubject<S>> {
        self._fields.0 = Option::Some(value.into());
        DismissMatchBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> DismissMatchBuilder<'a, S>
where
    S: dismiss_match_state::State,
    S::Subject: dismiss_match_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> DismissMatch<'a> {
        DismissMatch {
            subject: self._fields.0.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<SmolStr, Data<'a>>,
    ) -> DismissMatch<'a> {
        DismissMatch {
            subject: self._fields.0.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}