// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: sh.weaver.notebook.searchNotebooks
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

use crate::sh_weaver::notebook::NotebookView;
#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::ident::AtIdentifier;
use jacquard_common::types::value::Data;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};
use jacquard_derive::IntoStatic;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct SearchNotebooks<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub author: Option<AtIdentifier<S>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    /// Defaults to `25`. Min: 1. Max: 100.
    #[serde(default = "_default_limit")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    pub q: S,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rating: Option<Vec<S>>,
    /// Defaults to `"relevance"`.
    #[serde(default = "_default_sort")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sort: Option<S>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<S>>,
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct SearchNotebooksOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    pub notebooks: Vec<NotebookView<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `sh.weaver.notebook.searchNotebooks` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `SearchNotebooksOutput<S>` for this endpoint.*/
pub struct SearchNotebooksResponse;
impl jacquard_common::xrpc::XrpcResp for SearchNotebooksResponse {
    const NSID: &'static str = "sh.weaver.notebook.searchNotebooks";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = SearchNotebooksOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for SearchNotebooks<S> {
    const NSID: &'static str = "sh.weaver.notebook.searchNotebooks";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = SearchNotebooksResponse;
}

/** Endpoint marker for the `sh.weaver.notebook.searchNotebooks` query.

Path: `/xrpc/sh.weaver.notebook.searchNotebooks`. The request payload type is `SearchNotebooks<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct SearchNotebooksRequest;
impl jacquard_common::xrpc::XrpcEndpoint for SearchNotebooksRequest {
    const PATH: &'static str = "/xrpc/sh.weaver.notebook.searchNotebooks";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = SearchNotebooks<S>;
    type Response = SearchNotebooksResponse;
}

fn _default_limit() -> Option<i64> {
    Some(25i64)
}

fn _default_sort<S: jacquard_common::FromStaticStr>() -> Option<S> {
    Some(S::from_static("relevance"))
}

pub mod search_notebooks_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Q;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Q = Unset;
    }
    ///State transition - sets the `q` field to Set
    pub struct SetQ<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetQ<St> {}
    impl<St: State> State for SetQ<St> {
        type Q = Set<members::q>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `q` field
        pub struct q(());
    }
}

/// Builder for constructing an instance of this type.
pub struct SearchNotebooksBuilder<St: search_notebooks_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<AtIdentifier<S>>,
        Option<S>,
        Option<i64>,
        Option<S>,
        Option<Vec<S>>,
        Option<S>,
        Option<Vec<S>>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl SearchNotebooks<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> SearchNotebooksBuilder<search_notebooks_state::Empty, DefaultStr> {
        SearchNotebooksBuilder::new()
    }
}

impl<S: BosStr> SearchNotebooks<S> {
    /// Create a new builder for this type
    pub fn builder() -> SearchNotebooksBuilder<search_notebooks_state::Empty, S> {
        SearchNotebooksBuilder::builder()
    }
}

impl SearchNotebooksBuilder<search_notebooks_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        SearchNotebooksBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> SearchNotebooksBuilder<search_notebooks_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        SearchNotebooksBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St: search_notebooks_state::State, S: BosStr> SearchNotebooksBuilder<St, S> {
    /// Set the `author` field (optional)
    pub fn author(mut self, value: impl Into<Option<AtIdentifier<S>>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `author` field to an Option value (optional)
    pub fn maybe_author(mut self, value: Option<AtIdentifier<S>>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St: search_notebooks_state::State, S: BosStr> SearchNotebooksBuilder<St, S> {
    /// Set the `cursor` field (optional)
    pub fn cursor(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `cursor` field to an Option value (optional)
    pub fn maybe_cursor(mut self, value: Option<S>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St: search_notebooks_state::State, S: BosStr> SearchNotebooksBuilder<St, S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St, S: BosStr> SearchNotebooksBuilder<St, S>
where
    St: search_notebooks_state::State,
    St::Q: search_notebooks_state::IsUnset,
{
    /// Set the `q` field (required)
    pub fn q(
        mut self,
        value: impl Into<S>,
    ) -> SearchNotebooksBuilder<search_notebooks_state::SetQ<St>, S> {
        self._fields.3 = Option::Some(value.into());
        SearchNotebooksBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: search_notebooks_state::State, S: BosStr> SearchNotebooksBuilder<St, S> {
    /// Set the `rating` field (optional)
    pub fn rating(mut self, value: impl Into<Option<Vec<S>>>) -> Self {
        self._fields.4 = value.into();
        self
    }
    /// Set the `rating` field to an Option value (optional)
    pub fn maybe_rating(mut self, value: Option<Vec<S>>) -> Self {
        self._fields.4 = value;
        self
    }
}

impl<St: search_notebooks_state::State, S: BosStr> SearchNotebooksBuilder<St, S> {
    /// Set the `sort` field (optional)
    pub fn sort(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.5 = value.into();
        self
    }
    /// Set the `sort` field to an Option value (optional)
    pub fn maybe_sort(mut self, value: Option<S>) -> Self {
        self._fields.5 = value;
        self
    }
}

impl<St: search_notebooks_state::State, S: BosStr> SearchNotebooksBuilder<St, S> {
    /// Set the `tags` field (optional)
    pub fn tags(mut self, value: impl Into<Option<Vec<S>>>) -> Self {
        self._fields.6 = value.into();
        self
    }
    /// Set the `tags` field to an Option value (optional)
    pub fn maybe_tags(mut self, value: Option<Vec<S>>) -> Self {
        self._fields.6 = value;
        self
    }
}

impl<St, S: BosStr> SearchNotebooksBuilder<St, S>
where
    St: search_notebooks_state::State,
    St::Q: search_notebooks_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> SearchNotebooks<S> {
        SearchNotebooks {
            author: self._fields.0,
            cursor: self._fields.1,
            limit: self._fields.2,
            q: self._fields.3.unwrap(),
            rating: self._fields.4,
            sort: self._fields.5,
            tags: self._fields.6,
        }
    }
}
