// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: net.aftertheinter.coolthingtwo
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "net.aftertheinter.coolthingtwo",
    tag = "$type"
)]
pub struct Coolthingtwo<'a> {
    pub created_at: Datetime,
    #[serde(borrow)]
    pub status: CowStr<'a>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct CoolthingtwoGetRecordOutput<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub cid: Option<Cid<'a>>,
    #[serde(borrow)]
    pub uri: AtUri<'a>,
    #[serde(borrow)]
    pub value: Coolthingtwo<'a>,
}

impl<'a> Coolthingtwo<'a> {
    pub fn uri(
        uri: impl Into<CowStr<'a>>,
    ) -> Result<RecordUri<'a, CoolthingtwoRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new_cow(uri.into())?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct CoolthingtwoRecord;
impl XrpcResp for CoolthingtwoRecord {
    const NSID: &'static str = "net.aftertheinter.coolthingtwo";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = CoolthingtwoGetRecordOutput<'de>;
    type Err<'de> = RecordError<'de>;
}

impl From<CoolthingtwoGetRecordOutput<'_>> for Coolthingtwo<'_> {
    fn from(output: CoolthingtwoGetRecordOutput<'_>) -> Self {
        use jacquard_common::IntoStatic;
        output.value.into_static()
    }
}

impl Collection for Coolthingtwo<'_> {
    const NSID: &'static str = "net.aftertheinter.coolthingtwo";
    type Record = CoolthingtwoRecord;
}

impl Collection for CoolthingtwoRecord {
    const NSID: &'static str = "net.aftertheinter.coolthingtwo";
    type Record = CoolthingtwoRecord;
}

impl<'a> LexiconSchema for Coolthingtwo<'a> {
    fn nsid() -> &'static str {
        "net.aftertheinter.coolthingtwo"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_net_aftertheinter_coolthingtwo()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.status;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 32usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("status"),
                    max: 32usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.status;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) < 1usize {
                return Err(ConstraintError::MinLength {
                    path: ValidationPath::from_field("status"),
                    min: 1usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.status;
            {
                let count = UnicodeSegmentation::graphemes(value.as_ref(), true).count();
                if count > 1usize {
                    return Err(ConstraintError::MaxGraphemes {
                        path: ValidationPath::from_field("status"),
                        max: 1usize,
                        actual: count,
                    });
                }
            }
        }
        Ok(())
    }
}

pub mod coolthingtwo_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type CreatedAt;
        type Status;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type CreatedAt = Unset;
        type Status = Unset;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCreatedAt<S> {}
    impl<S: State> State for SetCreatedAt<S> {
        type CreatedAt = Set<members::created_at>;
        type Status = S::Status;
    }
    ///State transition - sets the `status` field to Set
    pub struct SetStatus<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetStatus<S> {}
    impl<S: State> State for SetStatus<S> {
        type CreatedAt = S::CreatedAt;
        type Status = Set<members::status>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `status` field
        pub struct status(());
    }
}

/// Builder for constructing an instance of this type
pub struct CoolthingtwoBuilder<'a, S: coolthingtwo_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<Datetime>, Option<CowStr<'a>>),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> Coolthingtwo<'a> {
    /// Create a new builder for this type
    pub fn new() -> CoolthingtwoBuilder<'a, coolthingtwo_state::Empty> {
        CoolthingtwoBuilder::new()
    }
}

impl<'a> CoolthingtwoBuilder<'a, coolthingtwo_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        CoolthingtwoBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> CoolthingtwoBuilder<'a, S>
where
    S: coolthingtwo_state::State,
    S::CreatedAt: coolthingtwo_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> CoolthingtwoBuilder<'a, coolthingtwo_state::SetCreatedAt<S>> {
        self._fields.0 = Option::Some(value.into());
        CoolthingtwoBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> CoolthingtwoBuilder<'a, S>
where
    S: coolthingtwo_state::State,
    S::Status: coolthingtwo_state::IsUnset,
{
    /// Set the `status` field (required)
    pub fn status(
        mut self,
        value: impl Into<CowStr<'a>>,
    ) -> CoolthingtwoBuilder<'a, coolthingtwo_state::SetStatus<S>> {
        self._fields.1 = Option::Some(value.into());
        CoolthingtwoBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> CoolthingtwoBuilder<'a, S>
where
    S: coolthingtwo_state::State,
    S::CreatedAt: coolthingtwo_state::IsSet,
    S::Status: coolthingtwo_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> Coolthingtwo<'a> {
        Coolthingtwo {
            created_at: self._fields.0.unwrap(),
            status: self._fields.1.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> Coolthingtwo<'a> {
        Coolthingtwo {
            created_at: self._fields.0.unwrap(),
            status: self._fields.1.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_net_aftertheinter_coolthingtwo() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("net.aftertheinter.coolthingtwo"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("status"),
                                SmolStr::new_static("createdAt")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("status"),
                                LexObjectProperty::String(LexString {
                                    min_length: Some(1usize),
                                    max_length: Some(32usize),
                                    max_graphemes: Some(1usize),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}