// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: sh.tangled.repo.issue
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

//! Generated bindings for the `sh.tangled.repo.issue` Lexicon namespace/module.
pub mod comment;
pub mod count_states;
pub mod count_states_by;
pub mod list_states;
pub mod list_states_by;
pub mod state;

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{BosStr, CowStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::blob::BlobRef;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime, Did};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "sh.tangled.repo.issue",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Issue<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub blobs: Option<Vec<BlobRef<S>>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub body: Option<S>,
    pub created_at: Datetime,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mentions: Option<Vec<Did<S>>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub references: Option<Vec<AtUri<S>>>,
    pub repo: Did<S>,
    pub title: S,
    #[serde(
        flatten,
        default,
        deserialize_with = "deserialize_issue_extra_data",
        skip_serializing_if = "Option::is_none"
    )]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct IssueGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: Issue<S>,
}

impl<S: BosStr> Issue<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, IssueRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct IssueRecord;
impl XrpcResp for IssueRecord {
    const NSID: &'static str = "sh.tangled.repo.issue";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = IssueGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<IssueGetRecordOutput<S>> for Issue<S> {
    fn from(output: IssueGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Issue<S> {
    const NSID: &'static str = "sh.tangled.repo.issue";
    type Record = IssueRecord;
}

impl Collection for IssueRecord {
    const NSID: &'static str = "sh.tangled.repo.issue";
    type Record = IssueRecord;
}

impl<S: BosStr> LexiconSchema for Issue<S> {
    fn nsid() -> &'static str {
        "sh.tangled.repo.issue"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_sh_tangled_repo_issue()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

fn deserialize_issue_extra_data<'de, S, D>(
    deserializer: D,
) -> Result<Option<BTreeMap<SmolStr, Data<S>>>, D::Error>
where
    S: BosStr + serde::Deserialize<'de>,
    D: serde::Deserializer<'de>,
{
    let mut data =
        <Option<BTreeMap<SmolStr, Data<S>>> as serde::Deserialize<'de>>::deserialize(deserializer)?;
    if let Some(extra_data) = &mut data {
        extra_data.remove("$type");
        if extra_data.is_empty() {
            data = None;
        }
    }
    Ok(data)
}

pub mod issue_state {

    pub use crate::builder_types::{IsSet, IsUnset, Set, Unset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type CreatedAt;
        type Repo;
        type Title;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type CreatedAt = Unset;
        type Repo = Unset;
        type Title = Unset;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetCreatedAt<St> {}
    impl<St: State> State for SetCreatedAt<St> {
        type CreatedAt = Set<members::created_at>;
        type Repo = St::Repo;
        type Title = St::Title;
    }
    ///State transition - sets the `repo` field to Set
    pub struct SetRepo<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetRepo<St> {}
    impl<St: State> State for SetRepo<St> {
        type CreatedAt = St::CreatedAt;
        type Repo = Set<members::repo>;
        type Title = St::Title;
    }
    ///State transition - sets the `title` field to Set
    pub struct SetTitle<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetTitle<St> {}
    impl<St: State> State for SetTitle<St> {
        type CreatedAt = St::CreatedAt;
        type Repo = St::Repo;
        type Title = Set<members::title>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `repo` field
        pub struct repo(());
        ///Marker type for the `title` field
        pub struct title(());
    }
}

/// Builder for constructing an instance of this type.
pub struct IssueBuilder<St: issue_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<Vec<BlobRef<S>>>,
        Option<S>,
        Option<Datetime>,
        Option<Vec<Did<S>>>,
        Option<Vec<AtUri<S>>>,
        Option<Did<S>>,
        Option<S>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl Issue<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> IssueBuilder<issue_state::Empty, DefaultStr> {
        IssueBuilder::new()
    }
}

impl<S: BosStr> Issue<S> {
    /// Create a new builder for this type
    pub fn builder() -> IssueBuilder<issue_state::Empty, S> {
        IssueBuilder::builder()
    }
}

impl IssueBuilder<issue_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        IssueBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> IssueBuilder<issue_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        IssueBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St: issue_state::State, S: BosStr> IssueBuilder<St, S> {
    /// Set the `blobs` field (optional)
    pub fn blobs(mut self, value: impl Into<Option<Vec<BlobRef<S>>>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `blobs` field to an Option value (optional)
    pub fn maybe_blobs(mut self, value: Option<Vec<BlobRef<S>>>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St: issue_state::State, S: BosStr> IssueBuilder<St, S> {
    /// Set the `body` field (optional)
    pub fn body(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `body` field to an Option value (optional)
    pub fn maybe_body(mut self, value: Option<S>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St, S: BosStr> IssueBuilder<St, S>
where
    St: issue_state::State,
    St::CreatedAt: issue_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> IssueBuilder<issue_state::SetCreatedAt<St>, S> {
        self._fields.2 = Option::Some(value.into());
        IssueBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: issue_state::State, S: BosStr> IssueBuilder<St, S> {
    /// Set the `mentions` field (optional)
    pub fn mentions(mut self, value: impl Into<Option<Vec<Did<S>>>>) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `mentions` field to an Option value (optional)
    pub fn maybe_mentions(mut self, value: Option<Vec<Did<S>>>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<St: issue_state::State, S: BosStr> IssueBuilder<St, S> {
    /// Set the `references` field (optional)
    pub fn references(mut self, value: impl Into<Option<Vec<AtUri<S>>>>) -> Self {
        self._fields.4 = value.into();
        self
    }
    /// Set the `references` field to an Option value (optional)
    pub fn maybe_references(mut self, value: Option<Vec<AtUri<S>>>) -> Self {
        self._fields.4 = value;
        self
    }
}

impl<St, S: BosStr> IssueBuilder<St, S>
where
    St: issue_state::State,
    St::Repo: issue_state::IsUnset,
{
    /// Set the `repo` field (required)
    pub fn repo(mut self, value: impl Into<Did<S>>) -> IssueBuilder<issue_state::SetRepo<St>, S> {
        self._fields.5 = Option::Some(value.into());
        IssueBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> IssueBuilder<St, S>
where
    St: issue_state::State,
    St::Title: issue_state::IsUnset,
{
    /// Set the `title` field (required)
    pub fn title(mut self, value: impl Into<S>) -> IssueBuilder<issue_state::SetTitle<St>, S> {
        self._fields.6 = Option::Some(value.into());
        IssueBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> IssueBuilder<St, S>
where
    St: issue_state::State,
    St::CreatedAt: issue_state::IsSet,
    St::Repo: issue_state::IsSet,
    St::Title: issue_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Issue<S> {
        Issue {
            blobs: self._fields.0,
            body: self._fields.1,
            created_at: self._fields.2.unwrap(),
            mentions: self._fields.3,
            references: self._fields.4,
            repo: self._fields.5.unwrap(),
            title: self._fields.6.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Issue<S> {
        Issue {
            blobs: self._fields.0,
            body: self._fields.1,
            created_at: self._fields.2.unwrap(),
            mentions: self._fields.3,
            references: self._fields.4,
            repo: self._fields.5.unwrap(),
            title: self._fields.6.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_sh_tangled_repo_issue() -> LexiconDoc<'static> {
    use alloc::collections::BTreeMap;
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("sh.tangled.repo.issue"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(vec![
                            SmolStr::new_static("repo"),
                            SmolStr::new_static("title"),
                            SmolStr::new_static("createdAt"),
                        ]),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("blobs"),
                                LexObjectProperty::Array(LexArray {
                                    items: LexArrayItem::Blob(LexBlob {
                                        ..Default::default()
                                    }),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("body"),
                                LexObjectProperty::String(LexString {
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("mentions"),
                                LexObjectProperty::Array(LexArray {
                                    items: LexArrayItem::String(LexString {
                                        format: Some(LexStringFormat::Did),
                                        ..Default::default()
                                    }),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("references"),
                                LexObjectProperty::Array(LexArray {
                                    items: LexArrayItem::String(LexString {
                                        format: Some(LexStringFormat::AtUri),
                                        ..Default::default()
                                    }),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("repo"),
                                LexObjectProperty::String(LexString {
                                    format: Some(LexStringFormat::Did),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("title"),
                                LexObjectProperty::String(LexString {
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}
