// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: sh.tangled.repo.merge
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::Did;
use jacquard_common::types::value::Data;
use jacquard_derive::IntoStatic;
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct Merge<S: BosStr = DefaultStr> {
    ///Author email for the merge commit
    #[serde(skip_serializing_if = "Option::is_none")]
    pub author_email: Option<S>,
    ///Author name for the merge commit
    #[serde(skip_serializing_if = "Option::is_none")]
    pub author_name: Option<S>,
    ///Target branch to merge into
    pub branch: S,
    ///Additional commit message body
    #[serde(skip_serializing_if = "Option::is_none")]
    pub commit_body: Option<S>,
    ///Merge commit message
    #[serde(skip_serializing_if = "Option::is_none")]
    pub commit_message: Option<S>,
    ///DID of the repository owner. A knot without the repo-did-input capability reads this and name in place of repo.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub did: Option<Did<S>>,
    ///Name of the repository. A knot without the repo-did-input capability reads this and DID in place of repo.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<S>,
    ///Patch content to merge
    pub patch: S,
    ///DID of the repository
    pub repo: Did<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `sh.tangled.repo.merge` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `()` for this endpoint.*/
pub struct MergeResponse;
impl jacquard_common::xrpc::XrpcResp for MergeResponse {
    const NSID: &'static str = "sh.tangled.repo.merge";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = ();
    type Err = jacquard_common::xrpc::GenericError;
    fn decode_output<'de, S>(
        body: &'de [u8],
    ) -> Result<Self::Output<S>, jacquard_common::error::DecodeError>
    where
        S: BosStr + Deserialize<'de>,
    {
        if body.is_empty() {
            Ok(())
        } else {
            Err(jacquard_common::error::DecodeError::UnexpectedBody)
        }
    }
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for Merge<S> {
    const NSID: &'static str = "sh.tangled.repo.merge";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = MergeResponse;
}

/** Endpoint marker for the `sh.tangled.repo.merge` procedure.

Path: `/xrpc/sh.tangled.repo.merge`. The request payload type is `Merge<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct MergeRequest;
impl jacquard_common::xrpc::XrpcEndpoint for MergeRequest {
    const PATH: &'static str = "/xrpc/sh.tangled.repo.merge";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<S: BosStr> = Merge<S>;
    type Response = MergeResponse;
}

pub mod merge_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Branch;
        type Patch;
        type Repo;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Branch = Unset;
        type Patch = Unset;
        type Repo = Unset;
    }
    ///State transition - sets the `branch` field to Set
    pub struct SetBranch<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetBranch<St> {}
    impl<St: State> State for SetBranch<St> {
        type Branch = Set<members::branch>;
        type Patch = St::Patch;
        type Repo = St::Repo;
    }
    ///State transition - sets the `patch` field to Set
    pub struct SetPatch<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetPatch<St> {}
    impl<St: State> State for SetPatch<St> {
        type Branch = St::Branch;
        type Patch = Set<members::patch>;
        type Repo = St::Repo;
    }
    ///State transition - sets the `repo` field to Set
    pub struct SetRepo<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetRepo<St> {}
    impl<St: State> State for SetRepo<St> {
        type Branch = St::Branch;
        type Patch = St::Patch;
        type Repo = Set<members::repo>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `branch` field
        pub struct branch(());
        ///Marker type for the `patch` field
        pub struct patch(());
        ///Marker type for the `repo` field
        pub struct repo(());
    }
}

/// Builder for constructing an instance of this type.
pub struct MergeBuilder<St: merge_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (
        Option<S>,
        Option<S>,
        Option<S>,
        Option<S>,
        Option<S>,
        Option<Did<S>>,
        Option<S>,
        Option<S>,
        Option<Did<S>>,
    ),
    _type: PhantomData<fn() -> S>,
}

impl Merge<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> MergeBuilder<merge_state::Empty, DefaultStr> {
        MergeBuilder::new()
    }
}

impl<S: BosStr> Merge<S> {
    /// Create a new builder for this type
    pub fn builder() -> MergeBuilder<merge_state::Empty, S> {
        MergeBuilder::builder()
    }
}

impl MergeBuilder<merge_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        MergeBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> MergeBuilder<merge_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        MergeBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None, None, None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St: merge_state::State, S: BosStr> MergeBuilder<St, S> {
    /// Set the `authorEmail` field (optional)
    pub fn author_email(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `authorEmail` field to an Option value (optional)
    pub fn maybe_author_email(mut self, value: Option<S>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St: merge_state::State, S: BosStr> MergeBuilder<St, S> {
    /// Set the `authorName` field (optional)
    pub fn author_name(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `authorName` field to an Option value (optional)
    pub fn maybe_author_name(mut self, value: Option<S>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St, S: BosStr> MergeBuilder<St, S>
where
    St: merge_state::State,
    St::Branch: merge_state::IsUnset,
{
    /// Set the `branch` field (required)
    pub fn branch(
        mut self,
        value: impl Into<S>,
    ) -> MergeBuilder<merge_state::SetBranch<St>, S> {
        self._fields.2 = Option::Some(value.into());
        MergeBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: merge_state::State, S: BosStr> MergeBuilder<St, S> {
    /// Set the `commitBody` field (optional)
    pub fn commit_body(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.3 = value.into();
        self
    }
    /// Set the `commitBody` field to an Option value (optional)
    pub fn maybe_commit_body(mut self, value: Option<S>) -> Self {
        self._fields.3 = value;
        self
    }
}

impl<St: merge_state::State, S: BosStr> MergeBuilder<St, S> {
    /// Set the `commitMessage` field (optional)
    pub fn commit_message(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.4 = value.into();
        self
    }
    /// Set the `commitMessage` field to an Option value (optional)
    pub fn maybe_commit_message(mut self, value: Option<S>) -> Self {
        self._fields.4 = value;
        self
    }
}

impl<St: merge_state::State, S: BosStr> MergeBuilder<St, S> {
    /// Set the `did` field (optional)
    pub fn did(mut self, value: impl Into<Option<Did<S>>>) -> Self {
        self._fields.5 = value.into();
        self
    }
    /// Set the `did` field to an Option value (optional)
    pub fn maybe_did(mut self, value: Option<Did<S>>) -> Self {
        self._fields.5 = value;
        self
    }
}

impl<St: merge_state::State, S: BosStr> MergeBuilder<St, S> {
    /// Set the `name` field (optional)
    pub fn name(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.6 = value.into();
        self
    }
    /// Set the `name` field to an Option value (optional)
    pub fn maybe_name(mut self, value: Option<S>) -> Self {
        self._fields.6 = value;
        self
    }
}

impl<St, S: BosStr> MergeBuilder<St, S>
where
    St: merge_state::State,
    St::Patch: merge_state::IsUnset,
{
    /// Set the `patch` field (required)
    pub fn patch(
        mut self,
        value: impl Into<S>,
    ) -> MergeBuilder<merge_state::SetPatch<St>, S> {
        self._fields.7 = Option::Some(value.into());
        MergeBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> MergeBuilder<St, S>
where
    St: merge_state::State,
    St::Repo: merge_state::IsUnset,
{
    /// Set the `repo` field (required)
    pub fn repo(
        mut self,
        value: impl Into<Did<S>>,
    ) -> MergeBuilder<merge_state::SetRepo<St>, S> {
        self._fields.8 = Option::Some(value.into());
        MergeBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> MergeBuilder<St, S>
where
    St: merge_state::State,
    St::Branch: merge_state::IsSet,
    St::Patch: merge_state::IsSet,
    St::Repo: merge_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Merge<S> {
        Merge {
            author_email: self._fields.0,
            author_name: self._fields.1,
            branch: self._fields.2.unwrap(),
            commit_body: self._fields.3,
            commit_message: self._fields.4,
            did: self._fields.5,
            name: self._fields.6,
            patch: self._fields.7.unwrap(),
            repo: self._fields.8.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Merge<S> {
        Merge {
            author_email: self._fields.0,
            author_name: self._fields.1,
            branch: self._fields.2.unwrap(),
            commit_body: self._fields.3,
            commit_message: self._fields.4,
            did: self._fields.5,
            name: self._fields.6,
            patch: self._fields.7.unwrap(),
            repo: self._fields.8.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}