[package]
name = "jacquard-oauth"
version = "0.8.0"
edition.workspace = true
description = "AT Protocol OAuth 2.1 core types and helpers for Jacquard"
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
exclude.workspace = true
license.workspace = true


[features]
default = []
loopback = ["dep:rouille"]
browser-open = ["dep:webbrowser"]
tracing = ["dep:tracing"]
websocket = ["jacquard-common/websocket"]
streaming = ["jacquard-common/streaming", "dep:n0-future"]

[dependencies]
jacquard-common = { version = "0.8", path = "../jacquard-common", features = ["reqwest-client"] }
jacquard-identity = { version = "0.8", path = "../jacquard-identity" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
url = { workspace = true }
smol_str = { workspace = true }
base64.workspace = true
sha2 = { version = "0.10" }
thiserror = { workspace = true }
serde_html_form = { workspace = true }
miette = { workspace = true }
p256 = { workspace = true, features = ["ecdsa"] }
signature = "2"
rand_core.workspace = true
jose-jwa = "0.1"
jose-jwk = { workspace = true, features = ["p256"] }
chrono.workspace = true
elliptic-curve = "0.13.8"
http.workspace = true
bytes.workspace = true
rand = { version = "0.8.5", features = ["small_rng"] }
dashmap = "6.1.0"
tokio = { workspace = true, default-features = false, features = ["sync"] }
reqwest.workspace = true
trait-variant.workspace = true
n0-future = { workspace = true, optional = true }
webbrowser = { version = "0.8", optional = true }
tracing = { workspace = true, optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["rt", "net", "time"] }
rouille = { version = "3.6.2", optional = true }
