[package]
name = "lazy-collections"
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
description.workspace = true

[features]
default = ["std", "tokio"]
std = [
    "alloc",
    "serde/std",
    "postcard/use-std",
    "miette",
    "chrono/std",
    "chrono/clock",
    "bytes/std",
    "serde_bytes/std",
    "embedded-io-async/std",
    "embedded-io/std",
    "dep:tokio",
    "dep:n0-future",
    "embedded-io-adapters/std",
    "maitake-sync/std"
]
alloc = [
    "serde/alloc",
    "serde_bytes/alloc",
    "chrono/alloc",
    "dep:bytes",
    "embedded-io/alloc",
    "embedded-io-async/alloc",
    "postcard/alloc",
    "maitake-sync/alloc",
]
tokio = [
    "embedded-io-adapters/tokio-1",
]

[dependencies]

serde.workspace = true
bytes = { workspace = true, optional = true }
chrono.workspace = true
serde_bytes.workspace = true
miette = { workspace = true, optional = true }
postcard = { version = "1.1.3", features = ["embedded-io-06"] }
embedded-io = { version = "0.6" }
embedded-io-async = { version = "0.6" }
embedded-io-adapters = { version = "0.6" }
maitake-sync = { version = "0.2", features = ["core-error"] }
tokio = { workspace = true, default-features = false, features = ["sync"], optional = true }
n0-future = { workspace = true, optional = true }
pin-project = "1"
heapless = "0.9"
managed = "0.8.0"
buffer = "0.1"
lock_api = "0.4"

tracing = { git = "https://github.com/tokio-rs/tracing", default-features = false, features = ["attributes"] }

[dev-dependencies]
proptest = "1"
tracing-subscriber = { git = "https://github.com/tokio-rs/tracing", features = ["fmt", "env-filter"]  }
tracing = { git = "https://github.com/tokio-rs/tracing", default-features = false, features = ["attributes", "std"] }


[target.'cfg(loom)'.dependencies]
loom = "0.7"


[target.'cfg(loom)'.dev-dependencies]
tracing_01 = { package = "tracing", version = "0.1.36" }
tracing-subscriber_03 = { package = "tracing-subscriber", version = "0.3.15", features = ["fmt", "env-filter"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(loom)']}
