[package]
name = "jacquard-common"
description = "Core AT Protocol types and utilities for Jacquard"
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
documentation = "https://docs.rs/jacquard-common"
exclude.workspace = true



[dependencies]
base64 = "0.22.1"
bytes.workspace = true
chrono = "0.4.42"
cid = { version = "0.11.1", features = ["serde", "std"] }
enum_dispatch = "0.3.13"
ipld-core = { version = "0.4.2", features = ["serde"] }
langtag = { version = "0.4.0", features = ["serde"] }
miette.workspace = true
multibase = "0.9.1"
multihash = "0.19.3"
num-traits = "0.2.19"
ouroboros = "0.18.5"
rand = "0.9.2"
regex = "1.11.3"
serde.workspace = true
serde_html_form.workspace = true
serde_json.workspace = true
serde_with.workspace = true
smol_str.workspace = true
thiserror.workspace = true
url.workspace = true
