[package]
name = "jacquard-common"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
cid = "0.11.1"
compact_str = "0.9.0"
multibase = "0.9.1"
multihash = "0.19.3"
regex = "1.11.3"
serde = { version = "1.0.227", features = ["derive"] }
