[package]
name = "jacquard-common"
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
documentation.workspace = true
exclude.workspace = true
description.workspace = true



[dependencies]
base64 = "0.22.1"
bytes = "1.10.1"
chrono = "0.4.42"
cid = { version = "0.11.1", features = ["serde", "std"] }
enum_dispatch = "0.3.13"
ipld-core = { version = "0.4.2", features = ["serde"] }
langtag = { version = "0.4.0", features = ["serde"] }
miette = "7.6.0"
multibase = "0.9.1"
multihash = "0.19.3"
num-traits = "0.2.19"
ouroboros = "0.18.5"
rand = "0.9.2"
regex = "1.11.3"
serde = { version = "1.0.227", features = ["derive"] }
serde_html_form = "0.2.8"
serde_json = "1.0.145"
serde_with = "3.14.1"
smol_str = { version = "0.3.2", features = ["serde"] }
thiserror = "2.0.16"
url = "2.5.7"
