[package]
name = "jacquard-common"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
chrono = "0.4.42"
cid = { version = "0.11.1", features = ["serde", "std"] }
langtag = { version = "0.4.0", features = ["serde"] }
miette = "7.6.0"
multibase = "0.9.1"
multihash = "0.19.3"
regex = "1.11.3"
serde = { version = "1.0.227", features = ["derive"] }
serde_html_form = "0.2.8"
serde_json = "1.0.145"
smol_str = { version = "0.3.2", features = ["serde"] }
thiserror = "2.0.16"
