// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: sh.tangled.graph.listVouchesBy
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::Did;
use jacquard_common::types::value::Data;
use jacquard_derive::IntoStatic;
use serde::{Serialize, Deserialize};
use crate::sh_tangled::graph::list_vouches::ListItem;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct ListVouchesBy<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    ///Defaults to `50`. Min: 1. Max: 1000.
    #[serde(default = "_default_limit")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    ///Defaults to `"desc"`.
    #[serde(default = "_default_order")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub order: Option<S>,
    pub subject: Did<S>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct ListVouchesByOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<S>,
    pub items: Vec<ListItem<S>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Response type for sh.tangled.graph.listVouchesBy
pub struct ListVouchesByResponse;
impl jacquard_common::xrpc::XrpcResp for ListVouchesByResponse {
    const NSID: &'static str = "sh.tangled.graph.listVouchesBy";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = ListVouchesByOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for ListVouchesBy<S> {
    const NSID: &'static str = "sh.tangled.graph.listVouchesBy";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = ListVouchesByResponse;
}

/// Endpoint type for sh.tangled.graph.listVouchesBy
pub struct ListVouchesByRequest;
impl jacquard_common::xrpc::XrpcEndpoint for ListVouchesByRequest {
    const PATH: &'static str = "/xrpc/sh.tangled.graph.listVouchesBy";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = ListVouchesBy<S>;
    type Response = ListVouchesByResponse;
}

fn _default_limit() -> Option<i64> {
    Some(50i64)
}

fn _default_order<S: jacquard_common::FromStaticStr>() -> Option<S> {
    Some(S::from_static("desc"))
}

pub mod list_vouches_by_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Subject;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Subject = Unset;
    }
    ///State transition - sets the `subject` field to Set
    pub struct SetSubject<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetSubject<St> {}
    impl<St: State> State for SetSubject<St> {
        type Subject = Set<members::subject>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `subject` field
        pub struct subject(());
    }
}

/// Builder for constructing an instance of this type.
pub struct ListVouchesByBuilder<
    St: list_vouches_by_state::State,
    S: BosStr = DefaultStr,
> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>, Option<i64>, Option<S>, Option<Did<S>>),
    _type: PhantomData<fn() -> S>,
}

impl ListVouchesBy<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> ListVouchesByBuilder<list_vouches_by_state::Empty, DefaultStr> {
        ListVouchesByBuilder::new()
    }
}

impl<S: BosStr> ListVouchesBy<S> {
    /// Create a new builder for this type
    pub fn builder() -> ListVouchesByBuilder<list_vouches_by_state::Empty, S> {
        ListVouchesByBuilder::builder()
    }
}

impl ListVouchesByBuilder<list_vouches_by_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        ListVouchesByBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> ListVouchesByBuilder<list_vouches_by_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        ListVouchesByBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St: list_vouches_by_state::State, S: BosStr> ListVouchesByBuilder<St, S> {
    /// Set the `cursor` field (optional)
    pub fn cursor(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `cursor` field to an Option value (optional)
    pub fn maybe_cursor(mut self, value: Option<S>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<St: list_vouches_by_state::State, S: BosStr> ListVouchesByBuilder<St, S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St: list_vouches_by_state::State, S: BosStr> ListVouchesByBuilder<St, S> {
    /// Set the `order` field (optional)
    pub fn order(mut self, value: impl Into<Option<S>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `order` field to an Option value (optional)
    pub fn maybe_order(mut self, value: Option<S>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St, S: BosStr> ListVouchesByBuilder<St, S>
where
    St: list_vouches_by_state::State,
    St::Subject: list_vouches_by_state::IsUnset,
{
    /// Set the `subject` field (required)
    pub fn subject(
        mut self,
        value: impl Into<Did<S>>,
    ) -> ListVouchesByBuilder<list_vouches_by_state::SetSubject<St>, S> {
        self._fields.3 = Option::Some(value.into());
        ListVouchesByBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> ListVouchesByBuilder<St, S>
where
    St: list_vouches_by_state::State,
    St::Subject: list_vouches_by_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> ListVouchesBy<S> {
        ListVouchesBy {
            cursor: self._fields.0,
            limit: self._fields.1,
            order: self._fields.2,
            subject: self._fields.3.unwrap(),
        }
    }
}