// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.shout.getShoutReplies
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{Bos, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::AtUri;
use jacquard_common::types::value::Data;
use jacquard_derive::IntoStatic;
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(
        serialize = "S: Serialize + BosStr",
        deserialize = "S: Deserialize<'de> + BosStr"
    )
)]
pub struct GetShoutReplies<S: BosStr = DefaultStr> {
    ///(min: 1)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    ///(min: 0)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
    pub uri: AtUri<S>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(
    rename_all = "camelCase",
    bound(
        serialize = "S: Serialize + BosStr",
        deserialize = "S: Deserialize<'de> + BosStr"
    )
)]
pub struct GetShoutRepliesOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub shouts: Option<Vec<Data<S>>>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Response type for app.rocksky.shout.getShoutReplies
pub struct GetShoutRepliesResponse;
impl jacquard_common::xrpc::XrpcResp for GetShoutRepliesResponse {
    const NSID: &'static str = "app.rocksky.shout.getShoutReplies";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetShoutRepliesOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetShoutReplies<S> {
    const NSID: &'static str = "app.rocksky.shout.getShoutReplies";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetShoutRepliesResponse;
}

/// Endpoint type for app.rocksky.shout.getShoutReplies
pub struct GetShoutRepliesRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetShoutRepliesRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.shout.getShoutReplies";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetShoutReplies<S>;
    type Response = GetShoutRepliesResponse;
}

pub mod get_shout_replies_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Uri;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Uri = Unset;
    }
    ///State transition - sets the `uri` field to Set
    pub struct SetUri<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetUri<St> {}
    impl<St: State> State for SetUri<St> {
        type Uri = Set<members::uri>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `uri` field
        pub struct uri(());
    }
}

/// Builder for constructing an instance of this type.
pub struct GetShoutRepliesBuilder<S: BosStr, St: get_shout_replies_state::State> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<i64>, Option<i64>, Option<AtUri<S>>),
    _type: PhantomData<fn() -> S>,
}

impl<S: BosStr> GetShoutReplies<S> {
    /// Create a new builder for this type.
    pub fn new() -> GetShoutRepliesBuilder<S, get_shout_replies_state::Empty> {
        GetShoutRepliesBuilder::new()
    }
}

impl<S: BosStr> GetShoutRepliesBuilder<S, get_shout_replies_state::Empty> {
    /// Create a new builder with all fields unset.
    pub fn new() -> Self {
        GetShoutRepliesBuilder {
            _state: PhantomData,
            _fields: (None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St: get_shout_replies_state::State> GetShoutRepliesBuilder<S, St> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<S: BosStr, St: get_shout_replies_state::State> GetShoutRepliesBuilder<S, St> {
    /// Set the `offset` field (optional)
    pub fn offset(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `offset` field to an Option value (optional)
    pub fn maybe_offset(mut self, value: Option<i64>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<S: BosStr, St> GetShoutRepliesBuilder<S, St>
where
    St: get_shout_replies_state::State,
    St::Uri: get_shout_replies_state::IsUnset,
{
    /// Set the `uri` field (required)
    pub fn uri(
        mut self,
        value: impl Into<AtUri<S>>,
    ) -> GetShoutRepliesBuilder<S, get_shout_replies_state::SetUri<St>> {
        self._fields.2 = Option::Some(value.into());
        GetShoutRepliesBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<S: BosStr, St> GetShoutRepliesBuilder<S, St>
where
    St: get_shout_replies_state::State,
    St::Uri: get_shout_replies_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> GetShoutReplies<S> {
        GetShoutReplies {
            limit: self._fields.0,
            offset: self._fields.1,
            uri: self._fields.2.unwrap(),
        }
    }
}