// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: com.atproto.temp.requestPhoneVerification
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    bon::Builder,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
#[builder(start_fn = new)]
pub struct RequestPhoneVerification<'a> {
    #[serde(borrow)]
    #[builder(into)]
    pub phone_number: jacquard_common::CowStr<'a>,
    #[serde(flatten)]
    #[serde(borrow)]
    #[builder(default)]
    pub extra_data: ::std::collections::BTreeMap<
        ::jacquard_common::smol_str::SmolStr,
        ::jacquard_common::types::value::Data<'a>,
    >,
}

///Response type for
///com.atproto.temp.requestPhoneVerification
pub struct RequestPhoneVerificationResponse;
impl jacquard_common::xrpc::XrpcResp for RequestPhoneVerificationResponse {
    const NSID: &'static str = "com.atproto.temp.requestPhoneVerification";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ();
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for RequestPhoneVerification<'a> {
    const NSID: &'static str = "com.atproto.temp.requestPhoneVerification";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = RequestPhoneVerificationResponse;
}

///Endpoint type for
///com.atproto.temp.requestPhoneVerification
pub struct RequestPhoneVerificationRequest;
impl jacquard_common::xrpc::XrpcEndpoint for RequestPhoneVerificationRequest {
    const PATH: &'static str = "/xrpc/com.atproto.temp.requestPhoneVerification";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = RequestPhoneVerification<'de>;
    type Response = RequestPhoneVerificationResponse;
}