when:
  - event: ["push", "pull_request"]
    branch: ["main"]

engine: nixery

dependencies:
  nixpkgs:
    - rustup
    - just
    - gcc

steps:
  - name: build crate
    command: |
      cargo build

  - name: check wasm compatibility
    command: |
      rustup target add wasm32-unknown-unknown
      cargo build -p jacquard-common \
        --target wasm32-unknown-unknown \
        --features streaming \
        --no-default-features
