when:
  - event: ["push", "pull_request"]
    branch: ["main"]

engine: nixery

dependencies:
  nixpkgs:
    - rustup
    - just
    - gcc

steps:
  - name: check basic wasm compatibility
    command: |
      rustup target add wasm32-unknown-unknown
      cargo build -p jacquard-common \
        --target wasm32-unknown-unknown \
        --features websocket \
        --no-default-features

  - name: run tests
    command: |
      cargo test
