when:
  - event: ["push", "pull_request"]
    branch: ["main"]

engine: nixery

dependencies:
  nixpkgs:
    - rustup
    - just
    - gcc

steps:
  - name: build crate
    command: |
      cargo build
