// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: social.flockfeeds.lexical.listitem
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

/// An list item, e.g. a step in a checklist or how-to description.
#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct Listitem<'a> {
    /** An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the
    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href="https://schema.org/docs/styleguide.html">style guide</a>.*/
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub additional_type: Option<jacquard_common::CowStr<'a>>,
    /// An alias for the item.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub alternate_name: Option<jacquard_common::CowStr<'a>>,
    /// A description of the item.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub description: Option<ListitemDescription<'a>>,
    /// A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub disambiguating_description: Option<jacquard_common::CowStr<'a>>,
    /// The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub identifier: Option<ListitemIdentifier<'a>>,
    /// An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub image: Option<ListitemImage<'a>>,
    /// An entity represented by an entry in a list or data feed (e.g. an 'artist' in a list of 'artists').
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub item: Option<ListitemItem<'a>>,
    /// Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub main_entity_of_page: Option<ListitemMainEntityOfPage<'a>>,
    /// The name of the item.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub name: Option<jacquard_common::CowStr<'a>>,
    /// A link to the ListItem that follows the current one.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub next_item: Option<ListitemNextItem<'a>>,
    /// The position of an item in a series or sequence of items.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub position: Option<jacquard_common::CowStr<'a>>,
    /// Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub potential_action: Option<ListitemPotentialAction<'a>>,
    /// A link to the ListItem that precedes the current one.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub previous_item: Option<ListitemPreviousItem<'a>>,
    /// URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub same_as: Option<jacquard_common::types::string::Uri<'a>>,
    /// A CreativeWork or Event about this Thing.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub subject_of: Option<ListitemSubjectOf<'a>>,
    /// URL of the item.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub url: Option<jacquard_common::types::string::Uri<'a>>,
}

pub mod listitem_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {}
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {}
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {}
}

/// Builder for constructing an instance of this type
pub struct ListitemBuilder<'a, S: listitem_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<ListitemDescription<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<ListitemIdentifier<'a>>,
        ::core::option::Option<ListitemImage<'a>>,
        ::core::option::Option<ListitemItem<'a>>,
        ::core::option::Option<ListitemMainEntityOfPage<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<ListitemNextItem<'a>>,
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<ListitemPotentialAction<'a>>,
        ::core::option::Option<ListitemPreviousItem<'a>>,
        ::core::option::Option<jacquard_common::types::string::Uri<'a>>,
        ::core::option::Option<ListitemSubjectOf<'a>>,
        ::core::option::Option<jacquard_common::types::string::Uri<'a>>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> Listitem<'a> {
    /// Create a new builder for this type
    pub fn new() -> ListitemBuilder<'a, listitem_state::Empty> {
        ListitemBuilder::new()
    }
}

impl<'a> ListitemBuilder<'a, listitem_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        ListitemBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
            ),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: listitem_state::State> ListitemBuilder<'a, S> {
    /// Set the `additionalType` field (optional)
    pub fn additional_type(
        mut self,
        value: impl Into<Option<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.0 = value.into();
        self
    }
    /// Set the `additionalType` field to an Option value (optional)
    pub fn maybe_additional_type(
        mut self,
        value: Option<jacquard_common::CowStr<'a>>,
    ) -> Self {
        self.__unsafe_private_named.0 = value;
        self
    }
}

impl<'a, S: listitem_state::State> ListitemBuilder<'a, S> {
    /// Set the `alternateName` field (optional)
    pub fn alternate_name(
        mut self,
        value: impl Into<Option<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.1 = value.into();
        self
    }
    /// Set the `alternateName` field to an Option value (optional)
    pub fn maybe_alternate_name(
        mut self,
        value: Option<jacquard_common::CowStr<'a>>,
    ) -> Self {
        self.__unsafe_private_named.1 = value;
        self
    }
}

impl<'a, S: listitem_state::State> ListitemBuilder<'a, S> {
    /// Set the `description` field (optional)
    pub fn description(
        mut self,
        value: impl Into<Option<ListitemDescription<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.2 = value.into();
        self
    }
    /// Set the `description` field to an Option value (optional)
    pub fn maybe_description(mut self, value: Option<ListitemDescription<'a>>) -> Self {
        self.__unsafe_private_named.2 = value;
        self
    }
}

impl<'a, S: listitem_state::State> ListitemBuilder<'a, S> {
    /// Set the `disambiguatingDescription` field (optional)
    pub fn disambiguating_description(
        mut self,
        value: impl Into<Option<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.3 = value.into();
        self
    }
    /// Set the `disambiguatingDescription` field to an Option value (optional)
    pub fn maybe_disambiguating_description(
        mut self,
        value: Option<jacquard_common::CowStr<'a>>,
    ) -> Self {
        self.__unsafe_private_named.3 = value;
        self
    }
}

impl<'a, S: listitem_state::State> ListitemBuilder<'a, S> {
    /// Set the `identifier` field (optional)
    pub fn identifier(
        mut self,
        value: impl Into<Option<ListitemIdentifier<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.4 = value.into();
        self
    }
    /// Set the `identifier` field to an Option value (optional)
    pub fn maybe_identifier(mut self, value: Option<ListitemIdentifier<'a>>) -> Self {
        self.__unsafe_private_named.4 = value;
        self
    }
}

impl<'a, S: listitem_state::State> ListitemBuilder<'a, S> {
    /// Set the `image` field (optional)
    pub fn image(mut self, value: impl Into<Option<ListitemImage<'a>>>) -> Self {
        self.__unsafe_private_named.5 = value.into();
        self
    }
    /// Set the `image` field to an Option value (optional)
    pub fn maybe_image(mut self, value: Option<ListitemImage<'a>>) -> Self {
        self.__unsafe_private_named.5 = value;
        self
    }
}

impl<'a, S: listitem_state::State> ListitemBuilder<'a, S> {
    /// Set the `item` field (optional)
    pub fn item(mut self, value: impl Into<Option<ListitemItem<'a>>>) -> Self {
        self.__unsafe_private_named.6 = value.into();
        self
    }
    /// Set the `item` field to an Option value (optional)
    pub fn maybe_item(mut self, value: Option<ListitemItem<'a>>) -> Self {
        self.__unsafe_private_named.6 = value;
        self
    }
}

impl<'a, S: listitem_state::State> ListitemBuilder<'a, S> {
    /// Set the `mainEntityOfPage` field (optional)
    pub fn main_entity_of_page(
        mut self,
        value: impl Into<Option<ListitemMainEntityOfPage<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.7 = value.into();
        self
    }
    /// Set the `mainEntityOfPage` field to an Option value (optional)
    pub fn maybe_main_entity_of_page(
        mut self,
        value: Option<ListitemMainEntityOfPage<'a>>,
    ) -> Self {
        self.__unsafe_private_named.7 = value;
        self
    }
}

impl<'a, S: listitem_state::State> ListitemBuilder<'a, S> {
    /// Set the `name` field (optional)
    pub fn name(
        mut self,
        value: impl Into<Option<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.8 = value.into();
        self
    }
    /// Set the `name` field to an Option value (optional)
    pub fn maybe_name(mut self, value: Option<jacquard_common::CowStr<'a>>) -> Self {
        self.__unsafe_private_named.8 = value;
        self
    }
}

impl<'a, S: listitem_state::State> ListitemBuilder<'a, S> {
    /// Set the `nextItem` field (optional)
    pub fn next_item(mut self, value: impl Into<Option<ListitemNextItem<'a>>>) -> Self {
        self.__unsafe_private_named.9 = value.into();
        self
    }
    /// Set the `nextItem` field to an Option value (optional)
    pub fn maybe_next_item(mut self, value: Option<ListitemNextItem<'a>>) -> Self {
        self.__unsafe_private_named.9 = value;
        self
    }
}

impl<'a, S: listitem_state::State> ListitemBuilder<'a, S> {
    /// Set the `position` field (optional)
    pub fn position(
        mut self,
        value: impl Into<Option<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.10 = value.into();
        self
    }
    /// Set the `position` field to an Option value (optional)
    pub fn maybe_position(mut self, value: Option<jacquard_common::CowStr<'a>>) -> Self {
        self.__unsafe_private_named.10 = value;
        self
    }
}

impl<'a, S: listitem_state::State> ListitemBuilder<'a, S> {
    /// Set the `potentialAction` field (optional)
    pub fn potential_action(
        mut self,
        value: impl Into<Option<ListitemPotentialAction<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.11 = value.into();
        self
    }
    /// Set the `potentialAction` field to an Option value (optional)
    pub fn maybe_potential_action(
        mut self,
        value: Option<ListitemPotentialAction<'a>>,
    ) -> Self {
        self.__unsafe_private_named.11 = value;
        self
    }
}

impl<'a, S: listitem_state::State> ListitemBuilder<'a, S> {
    /// Set the `previousItem` field (optional)
    pub fn previous_item(
        mut self,
        value: impl Into<Option<ListitemPreviousItem<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.12 = value.into();
        self
    }
    /// Set the `previousItem` field to an Option value (optional)
    pub fn maybe_previous_item(
        mut self,
        value: Option<ListitemPreviousItem<'a>>,
    ) -> Self {
        self.__unsafe_private_named.12 = value;
        self
    }
}

impl<'a, S: listitem_state::State> ListitemBuilder<'a, S> {
    /// Set the `sameAs` field (optional)
    pub fn same_as(
        mut self,
        value: impl Into<Option<jacquard_common::types::string::Uri<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.13 = value.into();
        self
    }
    /// Set the `sameAs` field to an Option value (optional)
    pub fn maybe_same_as(
        mut self,
        value: Option<jacquard_common::types::string::Uri<'a>>,
    ) -> Self {
        self.__unsafe_private_named.13 = value;
        self
    }
}

impl<'a, S: listitem_state::State> ListitemBuilder<'a, S> {
    /// Set the `subjectOf` field (optional)
    pub fn subject_of(
        mut self,
        value: impl Into<Option<ListitemSubjectOf<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.14 = value.into();
        self
    }
    /// Set the `subjectOf` field to an Option value (optional)
    pub fn maybe_subject_of(mut self, value: Option<ListitemSubjectOf<'a>>) -> Self {
        self.__unsafe_private_named.14 = value;
        self
    }
}

impl<'a, S: listitem_state::State> ListitemBuilder<'a, S> {
    /// Set the `url` field (optional)
    pub fn url(
        mut self,
        value: impl Into<Option<jacquard_common::types::string::Uri<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.15 = value.into();
        self
    }
    /// Set the `url` field to an Option value (optional)
    pub fn maybe_url(
        mut self,
        value: Option<jacquard_common::types::string::Uri<'a>>,
    ) -> Self {
        self.__unsafe_private_named.15 = value;
        self
    }
}

impl<'a, S> ListitemBuilder<'a, S>
where
    S: listitem_state::State,
{
    /// Build the final struct
    pub fn build(self) -> Listitem<'a> {
        Listitem {
            additional_type: self.__unsafe_private_named.0,
            alternate_name: self.__unsafe_private_named.1,
            description: self.__unsafe_private_named.2,
            disambiguating_description: self.__unsafe_private_named.3,
            identifier: self.__unsafe_private_named.4,
            image: self.__unsafe_private_named.5,
            item: self.__unsafe_private_named.6,
            main_entity_of_page: self.__unsafe_private_named.7,
            name: self.__unsafe_private_named.8,
            next_item: self.__unsafe_private_named.9,
            position: self.__unsafe_private_named.10,
            potential_action: self.__unsafe_private_named.11,
            previous_item: self.__unsafe_private_named.12,
            same_as: self.__unsafe_private_named.13,
            subject_of: self.__unsafe_private_named.14,
            url: self.__unsafe_private_named.15,
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: std::collections::BTreeMap<
            jacquard_common::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> Listitem<'a> {
        Listitem {
            additional_type: self.__unsafe_private_named.0,
            alternate_name: self.__unsafe_private_named.1,
            description: self.__unsafe_private_named.2,
            disambiguating_description: self.__unsafe_private_named.3,
            identifier: self.__unsafe_private_named.4,
            image: self.__unsafe_private_named.5,
            item: self.__unsafe_private_named.6,
            main_entity_of_page: self.__unsafe_private_named.7,
            name: self.__unsafe_private_named.8,
            next_item: self.__unsafe_private_named.9,
            position: self.__unsafe_private_named.10,
            potential_action: self.__unsafe_private_named.11,
            previous_item: self.__unsafe_private_named.12,
            same_as: self.__unsafe_private_named.13,
            subject_of: self.__unsafe_private_named.14,
            url: self.__unsafe_private_named.15,
            extra_data: Some(extra_data),
        }
    }
}

impl<'a> Listitem<'a> {
    pub fn uri(
        uri: impl Into<jacquard_common::CowStr<'a>>,
    ) -> Result<
        jacquard_common::types::uri::RecordUri<'a, ListitemRecord>,
        jacquard_common::types::uri::UriError,
    > {
        jacquard_common::types::uri::RecordUri::try_from_uri(
            jacquard_common::types::string::AtUri::new_cow(uri.into())?,
        )
    }
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "$type")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum ListitemDescription<'a> {
    #[serde(rename = "social.flockfeeds.lexical.textobject")]
    Textobject(Box<crate::social_flockfeeds::lexical::textobject::Textobject<'a>>),
    #[serde(rename = "social.flockfeeds.lexical.itemlist")]
    Itemlist(Box<crate::social_flockfeeds::lexical::itemlist::Itemlist<'a>>),
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "$type")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum ListitemIdentifier<'a> {
    #[serde(rename = "social.flockfeeds.lexical.propertyvalue")]
    Propertyvalue(
        Box<crate::social_flockfeeds::lexical::propertyvalue::Propertyvalue<'a>>,
    ),
    #[serde(rename = "social.flockfeeds.lexical.itemlist")]
    Itemlist(Box<crate::social_flockfeeds::lexical::itemlist::Itemlist<'a>>),
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "$type")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum ListitemImage<'a> {
    #[serde(rename = "social.flockfeeds.lexical.imageobject")]
    Imageobject(Box<crate::social_flockfeeds::lexical::imageobject::Imageobject<'a>>),
    #[serde(rename = "social.flockfeeds.lexical.itemlist")]
    Itemlist(Box<crate::social_flockfeeds::lexical::itemlist::Itemlist<'a>>),
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "$type")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum ListitemItem<'a> {
    #[serde(rename = "social.flockfeeds.lexical.thing")]
    Thing(Box<crate::social_flockfeeds::lexical::thing::Thing<'a>>),
    #[serde(rename = "social.flockfeeds.lexical.itemlist")]
    Itemlist(Box<crate::social_flockfeeds::lexical::itemlist::Itemlist<'a>>),
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "$type")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum ListitemMainEntityOfPage<'a> {
    #[serde(rename = "social.flockfeeds.lexical.creativework")]
    Creativework(Box<crate::social_flockfeeds::lexical::creativework::Creativework<'a>>),
    #[serde(rename = "social.flockfeeds.lexical.itemlist")]
    Itemlist(Box<crate::social_flockfeeds::lexical::itemlist::Itemlist<'a>>),
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "$type")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum ListitemNextItem<'a> {
    #[serde(rename = "social.flockfeeds.lexical.listitem")]
    Listitem(Box<crate::social_flockfeeds::lexical::listitem::Listitem<'a>>),
    #[serde(rename = "social.flockfeeds.lexical.itemlist")]
    Itemlist(Box<crate::social_flockfeeds::lexical::itemlist::Itemlist<'a>>),
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "$type")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum ListitemPotentialAction<'a> {
    #[serde(rename = "social.flockfeeds.lexical.action")]
    Action(Box<crate::social_flockfeeds::lexical::action::Action<'a>>),
    #[serde(rename = "social.flockfeeds.lexical.itemlist")]
    Itemlist(Box<crate::social_flockfeeds::lexical::itemlist::Itemlist<'a>>),
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "$type")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum ListitemPreviousItem<'a> {
    #[serde(rename = "social.flockfeeds.lexical.listitem")]
    Listitem(Box<crate::social_flockfeeds::lexical::listitem::Listitem<'a>>),
    #[serde(rename = "social.flockfeeds.lexical.itemlist")]
    Itemlist(Box<crate::social_flockfeeds::lexical::itemlist::Itemlist<'a>>),
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "$type")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum ListitemSubjectOf<'a> {
    #[serde(rename = "social.flockfeeds.lexical.event")]
    Event(Box<crate::social_flockfeeds::lexical::event::Event<'a>>),
    #[serde(rename = "social.flockfeeds.lexical.creativework")]
    Creativework(Box<crate::social_flockfeeds::lexical::creativework::Creativework<'a>>),
    #[serde(rename = "social.flockfeeds.lexical.itemlist")]
    Itemlist(Box<crate::social_flockfeeds::lexical::itemlist::Itemlist<'a>>),
}

/// Typed wrapper for GetRecord response with this collection's record type.
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct ListitemGetRecordOutput<'a> {
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub cid: std::option::Option<jacquard_common::types::string::Cid<'a>>,
    #[serde(borrow)]
    pub uri: jacquard_common::types::string::AtUri<'a>,
    #[serde(borrow)]
    pub value: Listitem<'a>,
}

impl From<ListitemGetRecordOutput<'_>> for Listitem<'_> {
    fn from(output: ListitemGetRecordOutput<'_>) -> Self {
        use jacquard_common::IntoStatic;
        output.value.into_static()
    }
}

impl jacquard_common::types::collection::Collection for Listitem<'_> {
    const NSID: &'static str = "social.flockfeeds.lexical.listitem";
    type Record = ListitemRecord;
}

/// Marker type for deserializing records from this collection.
#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct ListitemRecord;
impl jacquard_common::xrpc::XrpcResp for ListitemRecord {
    const NSID: &'static str = "social.flockfeeds.lexical.listitem";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ListitemGetRecordOutput<'de>;
    type Err<'de> = jacquard_common::types::collection::RecordError<'de>;
}

impl jacquard_common::types::collection::Collection for ListitemRecord {
    const NSID: &'static str = "social.flockfeeds.lexical.listitem";
    type Record = ListitemRecord;
}

impl<'a> ::jacquard_lexicon::schema::LexiconSchema for Listitem<'a> {
    fn nsid() -> &'static str {
        "social.flockfeeds.lexical.listitem"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> ::jacquard_lexicon::lexicon::LexiconDoc<'static> {
        lexicon_doc_social_flockfeeds_lexical_listitem()
    }
    fn validate(
        &self,
    ) -> ::std::result::Result<(), ::jacquard_lexicon::validation::ConstraintError> {
        Ok(())
    }
}

fn lexicon_doc_social_flockfeeds_lexical_listitem() -> ::jacquard_lexicon::lexicon::LexiconDoc<
    'static,
> {
    ::jacquard_lexicon::lexicon::LexiconDoc {
        lexicon: ::jacquard_lexicon::lexicon::Lexicon::Lexicon1,
        id: ::jacquard_common::CowStr::new_static("social.flockfeeds.lexical.listitem"),
        revision: None,
        description: None,
        defs: {
            let mut map = ::std::collections::BTreeMap::new();
            map.insert(
                ::jacquard_common::smol_str::SmolStr::new_static("main"),
                ::jacquard_lexicon::lexicon::LexUserType::Record(::jacquard_lexicon::lexicon::LexRecord {
                    description: Some(
                        ::jacquard_common::CowStr::new_static(
                            "An list item, e.g. a step in a checklist or how-to description.",
                        ),
                    ),
                    key: Some(::jacquard_common::CowStr::new_static("tid")),
                    record: ::jacquard_lexicon::lexicon::LexRecordRecord::Object(::jacquard_lexicon::lexicon::LexObject {
                        description: None,
                        required: None,
                        nullable: None,
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = ::std::collections::BTreeMap::new();
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "additionalType",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. Typically the value is a URI-identified RDF class, and in this case corresponds to the\n    use of rdf:type in RDF. Text values can be used sparingly, for cases where useful information can be added without their being an appropriate schema to reference. In the case of text values, the class label should follow the schema.org <a href=\"https://schema.org/docs/styleguide.html\">style guide</a>.",
                                        ),
                                    ),
                                    format: None,
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "alternateName",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "An alias for the item.",
                                        ),
                                    ),
                                    format: None,
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "description",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::Union(::jacquard_lexicon::lexicon::LexRefUnion {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "A description of the item.",
                                        ),
                                    ),
                                    refs: vec![
                                        ::jacquard_common::CowStr::new_static("social.flockfeeds.lexical.textobject"),
                                        ::jacquard_common::CowStr::new_static("social.flockfeeds.lexical.itemlist")
                                    ],
                                    closed: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "disambiguatingDescription",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "A sub property of description. A short description of the item used to disambiguate from other, similar items. Information from other properties (in particular, name) may be necessary for the description to be useful for disambiguation.",
                                        ),
                                    ),
                                    format: None,
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "identifier",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::Union(::jacquard_lexicon::lexicon::LexRefUnion {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "The identifier property represents any kind of identifier for any kind of [[Thing]], such as ISBNs, GTIN codes, UUIDs etc. Schema.org provides dedicated properties for representing many of these, either as textual strings or as URL (URI) links. See [background notes](/docs/datamodel.html#identifierBg) for more details.",
                                        ),
                                    ),
                                    refs: vec![
                                        ::jacquard_common::CowStr::new_static("social.flockfeeds.lexical.propertyvalue"),
                                        ::jacquard_common::CowStr::new_static("social.flockfeeds.lexical.itemlist")
                                    ],
                                    closed: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static("image"),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::Union(::jacquard_lexicon::lexicon::LexRefUnion {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "An image of the item. This can be a [[URL]] or a fully described [[ImageObject]].",
                                        ),
                                    ),
                                    refs: vec![
                                        ::jacquard_common::CowStr::new_static("social.flockfeeds.lexical.imageobject"),
                                        ::jacquard_common::CowStr::new_static("social.flockfeeds.lexical.itemlist")
                                    ],
                                    closed: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static("item"),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::Union(::jacquard_lexicon::lexicon::LexRefUnion {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "An entity represented by an entry in a list or data feed (e.g. an 'artist' in a list of 'artists').",
                                        ),
                                    ),
                                    refs: vec![
                                        ::jacquard_common::CowStr::new_static("social.flockfeeds.lexical.thing"),
                                        ::jacquard_common::CowStr::new_static("social.flockfeeds.lexical.itemlist")
                                    ],
                                    closed: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "mainEntityOfPage",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::Union(::jacquard_lexicon::lexicon::LexRefUnion {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "Indicates a page (or other CreativeWork) for which this thing is the main entity being described. See [background notes](/docs/datamodel.html#mainEntityBackground) for details.",
                                        ),
                                    ),
                                    refs: vec![
                                        ::jacquard_common::CowStr::new_static("social.flockfeeds.lexical.creativework"),
                                        ::jacquard_common::CowStr::new_static("social.flockfeeds.lexical.itemlist")
                                    ],
                                    closed: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static("name"),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "The name of the item.",
                                        ),
                                    ),
                                    format: None,
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "nextItem",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::Union(::jacquard_lexicon::lexicon::LexRefUnion {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "A link to the ListItem that follows the current one.",
                                        ),
                                    ),
                                    refs: vec![
                                        ::jacquard_common::CowStr::new_static("social.flockfeeds.lexical.listitem"),
                                        ::jacquard_common::CowStr::new_static("social.flockfeeds.lexical.itemlist")
                                    ],
                                    closed: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "position",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "The position of an item in a series or sequence of items.",
                                        ),
                                    ),
                                    format: None,
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "potentialAction",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::Union(::jacquard_lexicon::lexicon::LexRefUnion {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "Indicates a potential Action, which describes an idealized action in which this thing would play an 'object' role.",
                                        ),
                                    ),
                                    refs: vec![
                                        ::jacquard_common::CowStr::new_static("social.flockfeeds.lexical.action"),
                                        ::jacquard_common::CowStr::new_static("social.flockfeeds.lexical.itemlist")
                                    ],
                                    closed: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "previousItem",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::Union(::jacquard_lexicon::lexicon::LexRefUnion {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "A link to the ListItem that precedes the current one.",
                                        ),
                                    ),
                                    refs: vec![
                                        ::jacquard_common::CowStr::new_static("social.flockfeeds.lexical.listitem"),
                                        ::jacquard_common::CowStr::new_static("social.flockfeeds.lexical.itemlist")
                                    ],
                                    closed: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static("sameAs"),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.",
                                        ),
                                    ),
                                    format: Some(
                                        ::jacquard_lexicon::lexicon::LexStringFormat::Uri,
                                    ),
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static(
                                    "subjectOf",
                                ),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::Union(::jacquard_lexicon::lexicon::LexRefUnion {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static(
                                            "A CreativeWork or Event about this Thing.",
                                        ),
                                    ),
                                    refs: vec![
                                        ::jacquard_common::CowStr::new_static("social.flockfeeds.lexical.event"),
                                        ::jacquard_common::CowStr::new_static("social.flockfeeds.lexical.creativework"),
                                        ::jacquard_common::CowStr::new_static("social.flockfeeds.lexical.itemlist")
                                    ],
                                    closed: None,
                                }),
                            );
                            map.insert(
                                ::jacquard_common::smol_str::SmolStr::new_static("url"),
                                ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                    description: Some(
                                        ::jacquard_common::CowStr::new_static("URL of the item."),
                                    ),
                                    format: Some(
                                        ::jacquard_lexicon::lexicon::LexStringFormat::Uri,
                                    ),
                                    default: None,
                                    min_length: None,
                                    max_length: None,
                                    min_graphemes: None,
                                    max_graphemes: None,
                                    r#enum: None,
                                    r#const: None,
                                    known_values: None,
                                }),
                            );
                            map
                        },
                    }),
                }),
            );
            map
        },
    }
}