// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: place.stream.moderation.createBlock
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct CreateBlock<'a> {
    ///Optional reason for the block.
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub reason: std::option::Option<jacquard_common::CowStr<'a>>,
    ///The DID of the streamer whose chat this block applies to.
    #[serde(borrow)]
    pub streamer: jacquard_common::types::string::Did<'a>,
    ///The DID of the user being blocked from chat.
    #[serde(borrow)]
    pub subject: jacquard_common::types::string::Did<'a>,
}

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct CreateBlockOutput<'a> {
    ///The CID of the created block record.
    #[serde(borrow)]
    pub cid: jacquard_common::types::string::Cid<'a>,
    ///The AT-URI of the created block record.
    #[serde(borrow)]
    pub uri: jacquard_common::types::string::AtUri<'a>,
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum CreateBlockError<'a> {
    /// The request lacks valid authentication credentials.
    #[serde(rename = "Unauthorized")]
    Unauthorized(std::option::Option<jacquard_common::CowStr<'a>>),
    /// The caller does not have permission to create blocks for this streamer.
    #[serde(rename = "Forbidden")]
    Forbidden(std::option::Option<jacquard_common::CowStr<'a>>),
    /// The streamer's OAuth session could not be found or is invalid.
    #[serde(rename = "SessionNotFound")]
    SessionNotFound(std::option::Option<jacquard_common::CowStr<'a>>),
}

impl core::fmt::Display for CreateBlockError<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Unauthorized(msg) => {
                write!(f, "Unauthorized")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Forbidden(msg) => {
                write!(f, "Forbidden")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::SessionNotFound(msg) => {
                write!(f, "SessionNotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// Response type for
///place.stream.moderation.createBlock
pub struct CreateBlockResponse;
impl jacquard_common::xrpc::XrpcResp for CreateBlockResponse {
    const NSID: &'static str = "place.stream.moderation.createBlock";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = CreateBlockOutput<'de>;
    type Err<'de> = CreateBlockError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for CreateBlock<'a> {
    const NSID: &'static str = "place.stream.moderation.createBlock";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = CreateBlockResponse;
}

/// Endpoint type for
///place.stream.moderation.createBlock
pub struct CreateBlockRequest;
impl jacquard_common::xrpc::XrpcEndpoint for CreateBlockRequest {
    const PATH: &'static str = "/xrpc/place.stream.moderation.createBlock";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = CreateBlock<'de>;
    type Response = CreateBlockResponse;
}

pub mod create_block_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Streamer;
        type Subject;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Streamer = Unset;
        type Subject = Unset;
    }
    ///State transition - sets the `streamer` field to Set
    pub struct SetStreamer<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetStreamer<S> {}
    impl<S: State> State for SetStreamer<S> {
        type Streamer = Set<members::streamer>;
        type Subject = S::Subject;
    }
    ///State transition - sets the `subject` field to Set
    pub struct SetSubject<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetSubject<S> {}
    impl<S: State> State for SetSubject<S> {
        type Streamer = S::Streamer;
        type Subject = Set<members::subject>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `streamer` field
        pub struct streamer(());
        ///Marker type for the `subject` field
        pub struct subject(());
    }
}

/// Builder for constructing an instance of this type
pub struct CreateBlockBuilder<'a, S: create_block_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::CowStr<'a>>,
        ::core::option::Option<jacquard_common::types::string::Did<'a>>,
        ::core::option::Option<jacquard_common::types::string::Did<'a>>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> CreateBlock<'a> {
    /// Create a new builder for this type
    pub fn new() -> CreateBlockBuilder<'a, create_block_state::Empty> {
        CreateBlockBuilder::new()
    }
}

impl<'a> CreateBlockBuilder<'a, create_block_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        CreateBlockBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: create_block_state::State> CreateBlockBuilder<'a, S> {
    /// Set the `reason` field (optional)
    pub fn reason(
        mut self,
        value: impl Into<Option<jacquard_common::CowStr<'a>>>,
    ) -> Self {
        self.__unsafe_private_named.0 = value.into();
        self
    }
    /// Set the `reason` field to an Option value (optional)
    pub fn maybe_reason(mut self, value: Option<jacquard_common::CowStr<'a>>) -> Self {
        self.__unsafe_private_named.0 = value;
        self
    }
}

impl<'a, S> CreateBlockBuilder<'a, S>
where
    S: create_block_state::State,
    S::Streamer: create_block_state::IsUnset,
{
    /// Set the `streamer` field (required)
    pub fn streamer(
        mut self,
        value: impl Into<jacquard_common::types::string::Did<'a>>,
    ) -> CreateBlockBuilder<'a, create_block_state::SetStreamer<S>> {
        self.__unsafe_private_named.1 = ::core::option::Option::Some(value.into());
        CreateBlockBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> CreateBlockBuilder<'a, S>
where
    S: create_block_state::State,
    S::Subject: create_block_state::IsUnset,
{
    /// Set the `subject` field (required)
    pub fn subject(
        mut self,
        value: impl Into<jacquard_common::types::string::Did<'a>>,
    ) -> CreateBlockBuilder<'a, create_block_state::SetSubject<S>> {
        self.__unsafe_private_named.2 = ::core::option::Option::Some(value.into());
        CreateBlockBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> CreateBlockBuilder<'a, S>
where
    S: create_block_state::State,
    S::Streamer: create_block_state::IsSet,
    S::Subject: create_block_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> CreateBlock<'a> {
        CreateBlock {
            reason: self.__unsafe_private_named.0,
            streamer: self.__unsafe_private_named.1.unwrap(),
            subject: self.__unsafe_private_named.2.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: std::collections::BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> CreateBlock<'a> {
        CreateBlock {
            reason: self.__unsafe_private_named.0,
            streamer: self.__unsafe_private_named.1.unwrap(),
            subject: self.__unsafe_private_named.2.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}