// @generated by jacquard-lexicon. DO NOT EDIT.
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

//! Generated bindings for the `com..5jiji.test` Lexicon namespace/module.
pub mod list_videos;
pub mod publish_video;
pub mod videos;