[package]
name = "jacquard-lexgen"
description = "Lexicon fetching and code generation binaries for Jacquard"
edition.workspace = true
version = "0.11.1"
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
exclude.workspace = true
license.workspace = true

[[bin]]
name = "jacquard-codegen"
path = "src/bin/codegen.rs"

[[bin]]
name = "lex-fetch"
path = "src/bin/lex_fetch.rs"

[[bin]]
name = "extract-schemas"
path = "src/bin/extract_schemas.rs"

[[example]]
name = "extract_inventory"
path = "../../examples/extract_inventory.rs"


[dependencies]
clap.workspace = true
glob = "0.3"
inventory = "0.3"
jacquard-common = { version = "0.11", features = [ "reqwest-client" ], path = "../jacquard-common" }
jacquard-derive = { version = "0.11", path = "../jacquard-derive" }
jacquard-identity = { version = "0.11", path = "../jacquard-identity", features = ["dns"] }
jacquard-lexicon = { version = "0.11", path = "../jacquard-lexicon" }
kdl = "6"
miette = { workspace = true, features = ["fancy"] }
reqwest = { workspace = true, features = ["json", "http2", "system-proxy", "rustls-tls"] }
serde.workspace = true
serde_json = { workspace = true, features = ["preserve_order"] }
syn.workspace = true
tempfile = "3.23"
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
toml = "0.8"
walkdir = "2.5"

[dev-dependencies]
tempfile = { version = "3.23.0" }

[build-dependencies]
clap.workspace = true
clap_complete.workspace = true
clap_mangen.workspace = true

[package.metadata.binstall]
pkg-url = "https://github.com/rsform/jacquard/releases/download/v{ version }/{ name }_{ target }_v{ version }{ archive-suffix }"
bin-dir = "{ name }_{ target }_v{ version }/bin/{ bin }{ binary-ext }"
pkg-fmt = "txz"

[package.metadata.binstall.overrides.x86_64-pc-windows-gnu]
pkg-fmt = "zip"
bin-dir = "{ name }_{ target }_v{ version }/{ bin }{ binary-ext }"
