// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: social.psky.chat.message
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
use crate::com_atproto::repo::strong_ref::StrongRef;
use crate::social_psky::richtext::facet::Facet;
/// A Picosky message containing at most 2048 graphemes.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "social.psky.chat.message",
    tag = "$type",
    bound(deserialize = "S: Deserialize<'de> + BosStr")
)]
pub struct Message<S: BosStr = DefaultStr> {
    ///Text content.
    pub content: S,
    ///Annotations of text (mentions, URLs, hashtags, etc)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub facets: Option<Vec<Facet<S>>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reply: Option<StrongRef<S>>,
    pub room: AtUri<S>,
    #[serde(
        flatten,
        default,
        deserialize_with = "deserialize_message_extra_data",
        skip_serializing_if = "Option::is_none"
    )]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct MessageGetRecordOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: Message<S>,
}

impl<S: BosStr> Message<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, MessageRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct MessageRecord;
impl XrpcResp for MessageRecord {
    const NSID: &'static str = "social.psky.chat.message";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = MessageGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: BosStr> From<MessageGetRecordOutput<S>> for Message<S> {
    fn from(output: MessageGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: BosStr> Collection for Message<S> {
    const NSID: &'static str = "social.psky.chat.message";
    type Record = MessageRecord;
}

impl Collection for MessageRecord {
    const NSID: &'static str = "social.psky.chat.message";
    type Record = MessageRecord;
}

impl<S: BosStr> LexiconSchema for Message<S> {
    fn nsid() -> &'static str {
        "social.psky.chat.message"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_social_psky_chat_message()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.content;
            #[allow(unused_comparisons)]
            if <str>::len(value.as_ref()) > 20480usize {
                return Err(ConstraintError::MaxLength {
                    path: ValidationPath::from_field("content"),
                    max: 20480usize,
                    actual: <str>::len(value.as_ref()),
                });
            }
        }
        {
            let value = &self.content;
            {
                let count = UnicodeSegmentation::graphemes(value.as_ref(), true).count();
                if count > 2048usize {
                    return Err(ConstraintError::MaxGraphemes {
                        path: ValidationPath::from_field("content"),
                        max: 2048usize,
                        actual: count,
                    });
                }
            }
        }
        Ok(())
    }
}

fn deserialize_message_extra_data<'de, S, D>(
    deserializer: D,
) -> Result<Option<BTreeMap<SmolStr, Data<S>>>, D::Error>
where
    S: BosStr + serde::Deserialize<'de>,
    D: serde::Deserializer<'de>,
{
    let mut data = <Option<
        BTreeMap<SmolStr, Data<S>>,
    > as serde::Deserialize<'de>>::deserialize(deserializer)?;
    if let Some(extra_data) = &mut data {
        extra_data.remove("$type");
        if extra_data.is_empty() {
            data = None;
        }
    }
    Ok(data)
}

pub mod message_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Content;
        type Room;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Content = Unset;
        type Room = Unset;
    }
    ///State transition - sets the `content` field to Set
    pub struct SetContent<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetContent<St> {}
    impl<St: State> State for SetContent<St> {
        type Content = Set<members::content>;
        type Room = St::Room;
    }
    ///State transition - sets the `room` field to Set
    pub struct SetRoom<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetRoom<St> {}
    impl<St: State> State for SetRoom<St> {
        type Content = St::Content;
        type Room = Set<members::room>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `content` field
        pub struct content(());
        ///Marker type for the `room` field
        pub struct room(());
    }
}

/// Builder for constructing an instance of this type.
pub struct MessageBuilder<St: message_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<S>, Option<Vec<Facet<S>>>, Option<StrongRef<S>>, Option<AtUri<S>>),
    _type: PhantomData<fn() -> S>,
}

impl Message<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> MessageBuilder<message_state::Empty, DefaultStr> {
        MessageBuilder::new()
    }
}

impl<S: BosStr> Message<S> {
    /// Create a new builder for this type
    pub fn builder() -> MessageBuilder<message_state::Empty, S> {
        MessageBuilder::builder()
    }
}

impl MessageBuilder<message_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        MessageBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> MessageBuilder<message_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        MessageBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> MessageBuilder<St, S>
where
    St: message_state::State,
    St::Content: message_state::IsUnset,
{
    /// Set the `content` field (required)
    pub fn content(
        mut self,
        value: impl Into<S>,
    ) -> MessageBuilder<message_state::SetContent<St>, S> {
        self._fields.0 = Option::Some(value.into());
        MessageBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St: message_state::State, S: BosStr> MessageBuilder<St, S> {
    /// Set the `facets` field (optional)
    pub fn facets(mut self, value: impl Into<Option<Vec<Facet<S>>>>) -> Self {
        self._fields.1 = value.into();
        self
    }
    /// Set the `facets` field to an Option value (optional)
    pub fn maybe_facets(mut self, value: Option<Vec<Facet<S>>>) -> Self {
        self._fields.1 = value;
        self
    }
}

impl<St: message_state::State, S: BosStr> MessageBuilder<St, S> {
    /// Set the `reply` field (optional)
    pub fn reply(mut self, value: impl Into<Option<StrongRef<S>>>) -> Self {
        self._fields.2 = value.into();
        self
    }
    /// Set the `reply` field to an Option value (optional)
    pub fn maybe_reply(mut self, value: Option<StrongRef<S>>) -> Self {
        self._fields.2 = value;
        self
    }
}

impl<St, S: BosStr> MessageBuilder<St, S>
where
    St: message_state::State,
    St::Room: message_state::IsUnset,
{
    /// Set the `room` field (required)
    pub fn room(
        mut self,
        value: impl Into<AtUri<S>>,
    ) -> MessageBuilder<message_state::SetRoom<St>, S> {
        self._fields.3 = Option::Some(value.into());
        MessageBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> MessageBuilder<St, S>
where
    St: message_state::State,
    St::Content: message_state::IsSet,
    St::Room: message_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> Message<S> {
        Message {
            content: self._fields.0.unwrap(),
            facets: self._fields.1,
            reply: self._fields.2,
            room: self._fields.3.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(self, extra_data: BTreeMap<SmolStr, Data<S>>) -> Message<S> {
        Message {
            content: self._fields.0.unwrap(),
            facets: self._fields.1,
            reply: self._fields.2,
            room: self._fields.3.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_social_psky_chat_message() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("social.psky.chat.message"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    description: Some(
                        CowStr::new_static(
                            "A Picosky message containing at most 2048 graphemes.",
                        ),
                    ),
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("content"), SmolStr::new_static("room")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("content"),
                                LexObjectProperty::String(LexString {
                                    description: Some(CowStr::new_static("Text content.")),
                                    max_length: Some(20480usize),
                                    max_graphemes: Some(2048usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("facets"),
                                LexObjectProperty::Array(LexArray {
                                    description: Some(
                                        CowStr::new_static(
                                            "Annotations of text (mentions, URLs, hashtags, etc)",
                                        ),
                                    ),
                                    items: LexArrayItem::Ref(LexRef {
                                        r#ref: CowStr::new_static("social.psky.richtext.facet"),
                                        ..Default::default()
                                    }),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("reply"),
                                LexObjectProperty::Ref(LexRef {
                                    r#ref: CowStr::new_static("com.atproto.repo.strongRef"),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("room"),
                                LexObjectProperty::String(LexString {
                                    format: Some(LexStringFormat::AtUri),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}