// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.rocksky.actor.getActorArtists
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct GetActorArtists<'a> {
    #[serde(borrow)]
    pub did: jacquard_common::types::ident::AtIdentifier<'a>,
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub end_date: std::option::Option<jacquard_common::types::string::Datetime>,
    ///(min: 1)
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub limit: std::option::Option<i64>,
    ///(min: 0)
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub offset: std::option::Option<i64>,
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    pub start_date: std::option::Option<jacquard_common::types::string::Datetime>,
}

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic,
    Default
)]
#[serde(rename_all = "camelCase")]
pub struct GetActorArtistsOutput<'a> {
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub artists: std::option::Option<
        Vec<crate::app_rocksky::artist::ArtistViewBasic<'a>>,
    >,
}

/// Response type for
///app.rocksky.actor.getActorArtists
pub struct GetActorArtistsResponse;
impl jacquard_common::xrpc::XrpcResp for GetActorArtistsResponse {
    const NSID: &'static str = "app.rocksky.actor.getActorArtists";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = GetActorArtistsOutput<'de>;
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for GetActorArtists<'a> {
    const NSID: &'static str = "app.rocksky.actor.getActorArtists";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetActorArtistsResponse;
}

/// Endpoint type for
///app.rocksky.actor.getActorArtists
pub struct GetActorArtistsRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetActorArtistsRequest {
    const PATH: &'static str = "/xrpc/app.rocksky.actor.getActorArtists";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = GetActorArtists<'de>;
    type Response = GetActorArtistsResponse;
}

pub mod get_actor_artists_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Did;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Did = Unset;
    }
    ///State transition - sets the `did` field to Set
    pub struct SetDid<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDid<S> {}
    impl<S: State> State for SetDid<S> {
        type Did = Set<members::did>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `did` field
        pub struct did(());
    }
}

/// Builder for constructing an instance of this type
pub struct GetActorArtistsBuilder<'a, S: get_actor_artists_state::State> {
    _phantom_state: ::core::marker::PhantomData<fn() -> S>,
    __unsafe_private_named: (
        ::core::option::Option<jacquard_common::types::ident::AtIdentifier<'a>>,
        ::core::option::Option<jacquard_common::types::string::Datetime>,
        ::core::option::Option<i64>,
        ::core::option::Option<i64>,
        ::core::option::Option<jacquard_common::types::string::Datetime>,
    ),
    _phantom: ::core::marker::PhantomData<&'a ()>,
}

impl<'a> GetActorArtists<'a> {
    /// Create a new builder for this type
    pub fn new() -> GetActorArtistsBuilder<'a, get_actor_artists_state::Empty> {
        GetActorArtistsBuilder::new()
    }
}

impl<'a> GetActorArtistsBuilder<'a, get_actor_artists_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        GetActorArtistsBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: (None, None, None, None, None),
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S> GetActorArtistsBuilder<'a, S>
where
    S: get_actor_artists_state::State,
    S::Did: get_actor_artists_state::IsUnset,
{
    /// Set the `did` field (required)
    pub fn did(
        mut self,
        value: impl Into<jacquard_common::types::ident::AtIdentifier<'a>>,
    ) -> GetActorArtistsBuilder<'a, get_actor_artists_state::SetDid<S>> {
        self.__unsafe_private_named.0 = ::core::option::Option::Some(value.into());
        GetActorArtistsBuilder {
            _phantom_state: ::core::marker::PhantomData,
            __unsafe_private_named: self.__unsafe_private_named,
            _phantom: ::core::marker::PhantomData,
        }
    }
}

impl<'a, S: get_actor_artists_state::State> GetActorArtistsBuilder<'a, S> {
    /// Set the `endDate` field (optional)
    pub fn end_date(
        mut self,
        value: impl Into<Option<jacquard_common::types::string::Datetime>>,
    ) -> Self {
        self.__unsafe_private_named.1 = value.into();
        self
    }
    /// Set the `endDate` field to an Option value (optional)
    pub fn maybe_end_date(
        mut self,
        value: Option<jacquard_common::types::string::Datetime>,
    ) -> Self {
        self.__unsafe_private_named.1 = value;
        self
    }
}

impl<'a, S: get_actor_artists_state::State> GetActorArtistsBuilder<'a, S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self.__unsafe_private_named.2 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self.__unsafe_private_named.2 = value;
        self
    }
}

impl<'a, S: get_actor_artists_state::State> GetActorArtistsBuilder<'a, S> {
    /// Set the `offset` field (optional)
    pub fn offset(mut self, value: impl Into<Option<i64>>) -> Self {
        self.__unsafe_private_named.3 = value.into();
        self
    }
    /// Set the `offset` field to an Option value (optional)
    pub fn maybe_offset(mut self, value: Option<i64>) -> Self {
        self.__unsafe_private_named.3 = value;
        self
    }
}

impl<'a, S: get_actor_artists_state::State> GetActorArtistsBuilder<'a, S> {
    /// Set the `startDate` field (optional)
    pub fn start_date(
        mut self,
        value: impl Into<Option<jacquard_common::types::string::Datetime>>,
    ) -> Self {
        self.__unsafe_private_named.4 = value.into();
        self
    }
    /// Set the `startDate` field to an Option value (optional)
    pub fn maybe_start_date(
        mut self,
        value: Option<jacquard_common::types::string::Datetime>,
    ) -> Self {
        self.__unsafe_private_named.4 = value;
        self
    }
}

impl<'a, S> GetActorArtistsBuilder<'a, S>
where
    S: get_actor_artists_state::State,
    S::Did: get_actor_artists_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> GetActorArtists<'a> {
        GetActorArtists {
            did: self.__unsafe_private_named.0.unwrap(),
            end_date: self.__unsafe_private_named.1,
            limit: self.__unsafe_private_named.2,
            offset: self.__unsafe_private_named.3,
            start_date: self.__unsafe_private_named.4,
        }
    }
}