// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: pub.leaflet.document
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

/// Record containing a document
#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic,
    bon::Builder
)]
#[serde(rename_all = "camelCase")]
pub struct Document<'a> {
    #[serde(borrow)]
    pub author: jacquard_common::types::ident::AtIdentifier<'a>,
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[builder(into)]
    #[serde(borrow)]
    pub description: Option<jacquard_common::CowStr<'a>>,
    #[serde(borrow)]
    pub pages: Vec<DocumentPagesItem<'a>>,
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[builder(into)]
    #[serde(borrow)]
    pub post_ref: Option<crate::com_atproto::repo::strong_ref::StrongRef<'a>>,
    #[serde(borrow)]
    pub publication: jacquard_common::types::string::AtUri<'a>,
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[builder(into)]
    pub published_at: Option<jacquard_common::types::string::Datetime>,
    #[serde(borrow)]
    #[builder(into)]
    pub title: jacquard_common::CowStr<'a>,
}

impl<'a> Document<'a> {
    pub fn uri(
        uri: impl Into<jacquard_common::CowStr<'a>>,
    ) -> Result<
        jacquard_common::types::uri::RecordUri<'a, DocumentRecord>,
        jacquard_common::types::uri::UriError,
    > {
        jacquard_common::types::uri::RecordUri::try_from_uri(
            jacquard_common::types::string::AtUri::new_cow(uri.into())?,
        )
    }
}

#[jacquard_derive::open_union]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(tag = "$type")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum DocumentPagesItem<'a> {
    #[serde(rename = "pub.leaflet.pages.linearDocument")]
    LinearDocument(Box<crate::pub_leaflet::pages::linear_document::LinearDocument<'a>>),
    #[serde(rename = "pub.leaflet.pages.canvas")]
    Canvas(Box<crate::pub_leaflet::pages::canvas::Canvas<'a>>),
}

/// Typed wrapper for GetRecord response with this collection's record type.
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct DocumentGetRecordOutput<'a> {
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub cid: std::option::Option<jacquard_common::types::string::Cid<'a>>,
    #[serde(borrow)]
    pub uri: jacquard_common::types::string::AtUri<'a>,
    #[serde(borrow)]
    pub value: Document<'a>,
}

impl From<DocumentGetRecordOutput<'_>> for Document<'_> {
    fn from(output: DocumentGetRecordOutput<'_>) -> Self {
        use jacquard_common::IntoStatic;
        output.value.into_static()
    }
}

impl jacquard_common::types::collection::Collection for Document<'_> {
    const NSID: &'static str = "pub.leaflet.document";
    type Record = DocumentRecord;
}

/// Marker type for deserializing records from this collection.
#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct DocumentRecord;
impl jacquard_common::xrpc::XrpcResp for DocumentRecord {
    const NSID: &'static str = "pub.leaflet.document";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = DocumentGetRecordOutput<'de>;
    type Err<'de> = jacquard_common::types::collection::RecordError<'de>;
}

impl jacquard_common::types::collection::Collection for DocumentRecord {
    const NSID: &'static str = "pub.leaflet.document";
    type Record = DocumentRecord;
}

impl<'a> ::jacquard_lexicon::schema::LexiconSchema for Document<'a> {
    fn nsid() -> &'static str {
        "pub.leaflet.document"
    }
    fn lexicon_doc(
        _generator: &mut ::jacquard_lexicon::schema::LexiconGenerator,
    ) -> ::jacquard_lexicon::lexicon::LexiconDoc<'static> {
        ::jacquard_lexicon::lexicon::LexiconDoc {
            lexicon: ::jacquard_lexicon::lexicon::Lexicon::Lexicon1,
            id: "pub.leaflet.document".into(),
            revision: None,
            description: None,
            defs: {
                let mut map = ::std::collections::BTreeMap::new();
                map.insert(
                    "main".into(),
                    ::jacquard_lexicon::lexicon::LexUserType::Record(::jacquard_lexicon::lexicon::LexRecord {
                        description: None,
                        key: Some("tid".into()),
                        record: ::jacquard_lexicon::lexicon::LexRecordRecord::Object(::jacquard_lexicon::lexicon::LexObject {
                            description: None,
                            required: Some(
                                vec![
                                    "pages".into(), "author".into(), "title".into(),
                                    "publication".into()
                                ],
                            ),
                            nullable: None,
                            properties: {
                                let mut map = ::std::collections::BTreeMap::new();
                                map.insert(
                                    "author".into(),
                                    ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                        description: None,
                                        format: Some(
                                            ::jacquard_lexicon::lexicon::LexStringFormat::AtIdentifier,
                                        ),
                                        default: None,
                                        min_length: None,
                                        max_length: None,
                                        min_graphemes: None,
                                        max_graphemes: None,
                                        r#enum: None,
                                        r#const: None,
                                        known_values: None,
                                    }),
                                );
                                map.insert(
                                    "description".into(),
                                    ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                        description: None,
                                        format: None,
                                        default: None,
                                        min_length: None,
                                        max_length: Some(3000usize),
                                        min_graphemes: None,
                                        max_graphemes: Some(300usize),
                                        r#enum: None,
                                        r#const: None,
                                        known_values: None,
                                    }),
                                );
                                map.insert(
                                    "pages".into(),
                                    ::jacquard_lexicon::lexicon::LexObjectProperty::Array(::jacquard_lexicon::lexicon::LexArray {
                                        description: None,
                                        items: ::jacquard_lexicon::lexicon::LexArrayItem::Union(::jacquard_lexicon::lexicon::LexRefUnion {
                                            description: None,
                                            refs: vec![
                                                "pub.leaflet.pages.linearDocument".into(),
                                                "pub.leaflet.pages.canvas".into()
                                            ],
                                            closed: None,
                                        }),
                                        min_length: None,
                                        max_length: None,
                                    }),
                                );
                                map.insert(
                                    "postRef".into(),
                                    ::jacquard_lexicon::lexicon::LexObjectProperty::Ref(::jacquard_lexicon::lexicon::LexRef {
                                        description: None,
                                        r#ref: "com.atproto.repo.strongRef".into(),
                                    }),
                                );
                                map.insert(
                                    "publication".into(),
                                    ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                        description: None,
                                        format: Some(
                                            ::jacquard_lexicon::lexicon::LexStringFormat::AtUri,
                                        ),
                                        default: None,
                                        min_length: None,
                                        max_length: None,
                                        min_graphemes: None,
                                        max_graphemes: None,
                                        r#enum: None,
                                        r#const: None,
                                        known_values: None,
                                    }),
                                );
                                map.insert(
                                    "publishedAt".into(),
                                    ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                        description: None,
                                        format: Some(
                                            ::jacquard_lexicon::lexicon::LexStringFormat::Datetime,
                                        ),
                                        default: None,
                                        min_length: None,
                                        max_length: None,
                                        min_graphemes: None,
                                        max_graphemes: None,
                                        r#enum: None,
                                        r#const: None,
                                        known_values: None,
                                    }),
                                );
                                map.insert(
                                    "title".into(),
                                    ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                        description: None,
                                        format: None,
                                        default: None,
                                        min_length: None,
                                        max_length: Some(1280usize),
                                        min_graphemes: None,
                                        max_graphemes: Some(128usize),
                                        r#enum: None,
                                        r#const: None,
                                        known_values: None,
                                    }),
                                );
                                map
                            },
                        }),
                    }),
                );
                map
            },
        }
    }
    fn validate(
        &self,
    ) -> ::std::result::Result<(), ::jacquard_lexicon::schema::ValidationError> {
        if let Some(ref value) = self.description {
            if value.len() > 3000usize {
                return Err(::jacquard_lexicon::schema::ValidationError::MaxLength {
                    field: "description",
                    max: 3000usize,
                    actual: value.len(),
                });
            }
        }
        if let Some(ref value) = self.description {
            {
                let count = ::unicode_segmentation::UnicodeSegmentation::graphemes(
                        value.as_ref(),
                        true,
                    )
                    .count();
                if count > 300usize {
                    return Err(::jacquard_lexicon::schema::ValidationError::MaxGraphemes {
                        field: "description",
                        max: 300usize,
                        actual: count,
                    });
                }
            }
        }
        {
            let value = &self.title;
            if value.len() > 1280usize {
                return Err(::jacquard_lexicon::schema::ValidationError::MaxLength {
                    field: "title",
                    max: 1280usize,
                    actual: value.len(),
                });
            }
        }
        {
            let value = &self.title;
            {
                let count = ::unicode_segmentation::UnicodeSegmentation::graphemes(
                        value.as_ref(),
                        true,
                    )
                    .count();
                if count > 128usize {
                    return Err(::jacquard_lexicon::schema::ValidationError::MaxGraphemes {
                        field: "title",
                        max: 128usize,
                        actual: count,
                    });
                }
            }
        }
        Ok(())
    }
}