// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: sh.tangled.publicKey
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[jacquard_derive::lexicon]
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic,
    bon::Builder
)]
#[serde(rename_all = "camelCase")]
pub struct PublicKey<'a> {
    /// key upload timestamp
    pub created_at: jacquard_common::types::string::Datetime,
    /// public key contents
    #[serde(borrow)]
    #[builder(into)]
    pub key: jacquard_common::CowStr<'a>,
    /// human-readable name for this key
    #[serde(borrow)]
    #[builder(into)]
    pub name: jacquard_common::CowStr<'a>,
}

impl<'a> PublicKey<'a> {
    pub fn uri(
        uri: impl Into<jacquard_common::CowStr<'a>>,
    ) -> Result<
        jacquard_common::types::uri::RecordUri<'a, PublicKeyRecord>,
        jacquard_common::types::uri::UriError,
    > {
        jacquard_common::types::uri::RecordUri::try_from_uri(
            jacquard_common::types::string::AtUri::new_cow(uri.into())?,
        )
    }
}

/// Typed wrapper for GetRecord response with this collection's record type.
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    jacquard_derive::IntoStatic
)]
#[serde(rename_all = "camelCase")]
pub struct PublicKeyGetRecordOutput<'a> {
    #[serde(skip_serializing_if = "std::option::Option::is_none")]
    #[serde(borrow)]
    pub cid: std::option::Option<jacquard_common::types::string::Cid<'a>>,
    #[serde(borrow)]
    pub uri: jacquard_common::types::string::AtUri<'a>,
    #[serde(borrow)]
    pub value: PublicKey<'a>,
}

impl From<PublicKeyGetRecordOutput<'_>> for PublicKey<'_> {
    fn from(output: PublicKeyGetRecordOutput<'_>) -> Self {
        use jacquard_common::IntoStatic;
        output.value.into_static()
    }
}

impl jacquard_common::types::collection::Collection for PublicKey<'_> {
    const NSID: &'static str = "sh.tangled.publicKey";
    type Record = PublicKeyRecord;
}

/// Marker type for deserializing records from this collection.
#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct PublicKeyRecord;
impl jacquard_common::xrpc::XrpcResp for PublicKeyRecord {
    const NSID: &'static str = "sh.tangled.publicKey";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = PublicKeyGetRecordOutput<'de>;
    type Err<'de> = jacquard_common::types::collection::RecordError<'de>;
}

impl jacquard_common::types::collection::Collection for PublicKeyRecord {
    const NSID: &'static str = "sh.tangled.publicKey";
    type Record = PublicKeyRecord;
}

impl<'a> ::jacquard_lexicon::schema::LexiconSchema for PublicKey<'a> {
    fn nsid() -> &'static str {
        "sh.tangled.publicKey"
    }
    fn lexicon_doc(
        _generator: &mut ::jacquard_lexicon::schema::LexiconGenerator,
    ) -> ::jacquard_lexicon::lexicon::LexiconDoc<'static> {
        ::jacquard_lexicon::lexicon::LexiconDoc {
            lexicon: ::jacquard_lexicon::lexicon::Lexicon::Lexicon1,
            id: "sh.tangled.publicKey".into(),
            revision: None,
            description: None,
            defs: {
                let mut map = ::std::collections::BTreeMap::new();
                map.insert(
                    "main".into(),
                    ::jacquard_lexicon::lexicon::LexUserType::Record(::jacquard_lexicon::lexicon::LexRecord {
                        description: None,
                        key: Some("tid".into()),
                        record: ::jacquard_lexicon::lexicon::LexRecordRecord::Object(::jacquard_lexicon::lexicon::LexObject {
                            description: None,
                            required: Some(
                                vec!["key".into(), "name".into(), "createdAt".into()],
                            ),
                            nullable: None,
                            properties: {
                                let mut map = ::std::collections::BTreeMap::new();
                                map.insert(
                                    "createdAt".into(),
                                    ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                        description: None,
                                        format: Some(
                                            ::jacquard_lexicon::lexicon::LexStringFormat::Datetime,
                                        ),
                                        default: None,
                                        min_length: None,
                                        max_length: None,
                                        min_graphemes: None,
                                        max_graphemes: None,
                                        r#enum: None,
                                        r#const: None,
                                        known_values: None,
                                    }),
                                );
                                map.insert(
                                    "key".into(),
                                    ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                        description: None,
                                        format: None,
                                        default: None,
                                        min_length: None,
                                        max_length: Some(4096usize),
                                        min_graphemes: None,
                                        max_graphemes: None,
                                        r#enum: None,
                                        r#const: None,
                                        known_values: None,
                                    }),
                                );
                                map.insert(
                                    "name".into(),
                                    ::jacquard_lexicon::lexicon::LexObjectProperty::String(::jacquard_lexicon::lexicon::LexString {
                                        description: None,
                                        format: None,
                                        default: None,
                                        min_length: None,
                                        max_length: None,
                                        min_graphemes: None,
                                        max_graphemes: None,
                                        r#enum: None,
                                        r#const: None,
                                        known_values: None,
                                    }),
                                );
                                map
                            },
                        }),
                    }),
                );
                map
            },
        }
    }
    fn validate(
        &self,
    ) -> ::std::result::Result<(), ::jacquard_lexicon::schema::ValidationError> {
        {
            let value = &self.key;
            if value.len() > 4096usize {
                return Err(::jacquard_lexicon::schema::ValidationError::MaxLength {
                    field: "key",
                    max: 4096usize,
                    actual: value.len(),
                });
            }
        }
        Ok(())
    }
}