// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: sh.tangled.string
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, Bos, DefaultStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::collection::{Collection, RecordError};
use jacquard_common::types::string::{AtUri, Cid, Datetime};
use jacquard_common::types::uri::{RecordUri, UriError};
use jacquard_common::types::value::Data;
use jacquard_common::xrpc::XrpcResp;
use jacquard_derive::{IntoStatic, lexicon};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    rename = "sh.tangled.string",
    tag = "$type",
    bound(
        serialize = "S: Serialize + Bos<str> + AsRef<str>",
        deserialize = "S: Deserialize<'de> + Bos<str> + AsRef<str>"
    )
)]
pub struct TangledString<S: Bos<str> + AsRef<str> = DefaultStr> {
    pub contents: S,
    pub created_at: Datetime,
    pub description: S,
    pub filename: S,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Typed wrapper for GetRecord response with this collection's record type.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(
    rename_all = "camelCase",
    bound(
        serialize = "S: Serialize + Bos<str> + AsRef<str>",
        deserialize = "S: Deserialize<'de> + Bos<str> + AsRef<str>"
    )
)]
pub struct TangledStringGetRecordOutput<S: Bos<str> + AsRef<str> = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cid: Option<Cid<S>>,
    pub uri: AtUri<S>,
    pub value: TangledString<S>,
}

impl<S: Bos<str> + AsRef<str>> TangledString<S> {
    pub fn uri(uri: S) -> Result<RecordUri<S, TangledStringRecord>, UriError> {
        RecordUri::try_from_uri(AtUri::new(uri)?)
    }
}

/// Marker type for deserializing records from this collection.

#[derive(Debug, Serialize, Deserialize)]
pub struct TangledStringRecord;
impl XrpcResp for TangledStringRecord {
    const NSID: &'static str = "sh.tangled.string";
    const ENCODING: &'static str = "application/json";
    type Output<S: Bos<str> + AsRef<str>> = TangledStringGetRecordOutput<S>;
    type Err = RecordError;
}

impl<S: Bos<str> + AsRef<str>> From<TangledStringGetRecordOutput<S>>
for TangledString<S> {
    fn from(output: TangledStringGetRecordOutput<S>) -> Self {
        output.value
    }
}

impl<S: Bos<str> + AsRef<str>> Collection for TangledString<S> {
    const NSID: &'static str = "sh.tangled.string";
    type Record = TangledStringRecord;
}

impl Collection for TangledStringRecord {
    const NSID: &'static str = "sh.tangled.string";
    type Record = TangledStringRecord;
}

impl<S: Bos<str> + AsRef<str>> LexiconSchema for TangledString<S> {
    fn nsid() -> &'static str {
        "sh.tangled.string"
    }
    fn def_name() -> &'static str {
        "main"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_sh_tangled_string()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.contents;
            {
                let count = UnicodeSegmentation::graphemes(value.as_ref(), true).count();
                if count < 1usize {
                    return Err(ConstraintError::MinGraphemes {
                        path: ValidationPath::from_field("contents"),
                        min: 1usize,
                        actual: count,
                    });
                }
            }
        }
        {
            let value = &self.description;
            {
                let count = UnicodeSegmentation::graphemes(value.as_ref(), true).count();
                if count > 280usize {
                    return Err(ConstraintError::MaxGraphemes {
                        path: ValidationPath::from_field("description"),
                        max: 280usize,
                        actual: count,
                    });
                }
            }
        }
        {
            let value = &self.filename;
            {
                let count = UnicodeSegmentation::graphemes(value.as_ref(), true).count();
                if count > 140usize {
                    return Err(ConstraintError::MaxGraphemes {
                        path: ValidationPath::from_field("filename"),
                        max: 140usize,
                        actual: count,
                    });
                }
            }
        }
        {
            let value = &self.filename;
            {
                let count = UnicodeSegmentation::graphemes(value.as_ref(), true).count();
                if count < 1usize {
                    return Err(ConstraintError::MinGraphemes {
                        path: ValidationPath::from_field("filename"),
                        min: 1usize,
                        actual: count,
                    });
                }
            }
        }
        Ok(())
    }
}

pub mod tangled_string_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Filename;
        type Contents;
        type CreatedAt;
        type Description;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Filename = Unset;
        type Contents = Unset;
        type CreatedAt = Unset;
        type Description = Unset;
    }
    ///State transition - sets the `filename` field to Set
    pub struct SetFilename<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetFilename<S> {}
    impl<S: State> State for SetFilename<S> {
        type Filename = Set<members::filename>;
        type Contents = S::Contents;
        type CreatedAt = S::CreatedAt;
        type Description = S::Description;
    }
    ///State transition - sets the `contents` field to Set
    pub struct SetContents<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetContents<S> {}
    impl<S: State> State for SetContents<S> {
        type Filename = S::Filename;
        type Contents = Set<members::contents>;
        type CreatedAt = S::CreatedAt;
        type Description = S::Description;
    }
    ///State transition - sets the `created_at` field to Set
    pub struct SetCreatedAt<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCreatedAt<S> {}
    impl<S: State> State for SetCreatedAt<S> {
        type Filename = S::Filename;
        type Contents = S::Contents;
        type CreatedAt = Set<members::created_at>;
        type Description = S::Description;
    }
    ///State transition - sets the `description` field to Set
    pub struct SetDescription<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDescription<S> {}
    impl<S: State> State for SetDescription<S> {
        type Filename = S::Filename;
        type Contents = S::Contents;
        type CreatedAt = S::CreatedAt;
        type Description = Set<members::description>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `filename` field
        pub struct filename(());
        ///Marker type for the `contents` field
        pub struct contents(());
        ///Marker type for the `created_at` field
        pub struct created_at(());
        ///Marker type for the `description` field
        pub struct description(());
    }
}

/// Builder for constructing an instance of this type
pub struct TangledStringBuilder<'a, S: tangled_string_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<S>, Option<Datetime>, Option<S>, Option<S>),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> TangledString<'a> {
    /// Create a new builder for this type
    pub fn new() -> TangledStringBuilder<'a, tangled_string_state::Empty> {
        TangledStringBuilder::new()
    }
}

impl<'a> TangledStringBuilder<'a, tangled_string_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        TangledStringBuilder {
            _state: PhantomData,
            _fields: (None, None, None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> TangledStringBuilder<'a, S>
where
    S: tangled_string_state::State,
    S::Contents: tangled_string_state::IsUnset,
{
    /// Set the `contents` field (required)
    pub fn contents(
        mut self,
        value: impl Into<S>,
    ) -> TangledStringBuilder<'a, tangled_string_state::SetContents<S>> {
        self._fields.0 = Option::Some(value.into());
        TangledStringBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> TangledStringBuilder<'a, S>
where
    S: tangled_string_state::State,
    S::CreatedAt: tangled_string_state::IsUnset,
{
    /// Set the `createdAt` field (required)
    pub fn created_at(
        mut self,
        value: impl Into<Datetime>,
    ) -> TangledStringBuilder<'a, tangled_string_state::SetCreatedAt<S>> {
        self._fields.1 = Option::Some(value.into());
        TangledStringBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> TangledStringBuilder<'a, S>
where
    S: tangled_string_state::State,
    S::Description: tangled_string_state::IsUnset,
{
    /// Set the `description` field (required)
    pub fn description(
        mut self,
        value: impl Into<S>,
    ) -> TangledStringBuilder<'a, tangled_string_state::SetDescription<S>> {
        self._fields.2 = Option::Some(value.into());
        TangledStringBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> TangledStringBuilder<'a, S>
where
    S: tangled_string_state::State,
    S::Filename: tangled_string_state::IsUnset,
{
    /// Set the `filename` field (required)
    pub fn filename(
        mut self,
        value: impl Into<S>,
    ) -> TangledStringBuilder<'a, tangled_string_state::SetFilename<S>> {
        self._fields.3 = Option::Some(value.into());
        TangledStringBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> TangledStringBuilder<'a, S>
where
    S: tangled_string_state::State,
    S::Filename: tangled_string_state::IsSet,
    S::Contents: tangled_string_state::IsSet,
    S::CreatedAt: tangled_string_state::IsSet,
    S::Description: tangled_string_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> TangledString<'a> {
        TangledString {
            contents: self._fields.0.unwrap(),
            created_at: self._fields.1.unwrap(),
            description: self._fields.2.unwrap(),
            filename: self._fields.3.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<SmolStr, Data<'a>>,
    ) -> TangledString<'a> {
        TangledString {
            contents: self._fields.0.unwrap(),
            created_at: self._fields.1.unwrap(),
            description: self._fields.2.unwrap(),
            filename: self._fields.3.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_sh_tangled_string() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("sh.tangled.string"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::Record(LexRecord {
                    key: Some(CowStr::new_static("tid")),
                    record: LexRecordRecord::Object(LexObject {
                        required: Some(
                            vec![
                                SmolStr::new_static("filename"),
                                SmolStr::new_static("description"),
                                SmolStr::new_static("createdAt"),
                                SmolStr::new_static("contents")
                            ],
                        ),
                        properties: {
                            #[allow(unused_mut)]
                            let mut map = BTreeMap::new();
                            map.insert(
                                SmolStr::new_static("contents"),
                                LexObjectProperty::String(LexString {
                                    min_graphemes: Some(1usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("createdAt"),
                                LexObjectProperty::String(LexString {
                                    format: Some(LexStringFormat::Datetime),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("description"),
                                LexObjectProperty::String(LexString {
                                    max_graphemes: Some(280usize),
                                    ..Default::default()
                                }),
                            );
                            map.insert(
                                SmolStr::new_static("filename"),
                                LexObjectProperty::String(LexString {
                                    min_graphemes: Some(1usize),
                                    max_graphemes: Some(140usize),
                                    ..Default::default()
                                }),
                            );
                            map
                        },
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}