// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: social.clippr.feed.getTagList
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::types::ident::AtIdentifier;
use jacquard_derive::{IntoStatic, lexicon};
use serde::{Serialize, Deserialize};
use crate::social_clippr::feed::TagView;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct GetTagList<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub actor: Option<AtIdentifier<'a>>,
}


#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct GetTagListOutput<'a> {
    ///A list of tags and their associated details
    #[serde(borrow)]
    pub tags: Vec<TagView<'a>>,
}

/// Response type for social.clippr.feed.getTagList
pub struct GetTagListResponse;
impl jacquard_common::xrpc::XrpcResp for GetTagListResponse {
    const NSID: &'static str = "social.clippr.feed.getTagList";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = GetTagListOutput<'de>;
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for GetTagList<'a> {
    const NSID: &'static str = "social.clippr.feed.getTagList";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetTagListResponse;
}

/// Endpoint type for social.clippr.feed.getTagList
pub struct GetTagListRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetTagListRequest {
    const PATH: &'static str = "/xrpc/social.clippr.feed.getTagList";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = GetTagList<'de>;
    type Response = GetTagListResponse;
}

pub mod get_tag_list_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {}
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {}
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {}
}

/// Builder for constructing an instance of this type
pub struct GetTagListBuilder<'a, S: get_tag_list_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<AtIdentifier<'a>>,),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> GetTagList<'a> {
    /// Create a new builder for this type
    pub fn new() -> GetTagListBuilder<'a, get_tag_list_state::Empty> {
        GetTagListBuilder::new()
    }
}

impl<'a> GetTagListBuilder<'a, get_tag_list_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        GetTagListBuilder {
            _state: PhantomData,
            _fields: (None,),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S: get_tag_list_state::State> GetTagListBuilder<'a, S> {
    /// Set the `actor` field (optional)
    pub fn actor(mut self, value: impl Into<Option<AtIdentifier<'a>>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `actor` field to an Option value (optional)
    pub fn maybe_actor(mut self, value: Option<AtIdentifier<'a>>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<'a, S> GetTagListBuilder<'a, S>
where
    S: get_tag_list_state::State,
{
    /// Build the final struct
    pub fn build(self) -> GetTagList<'a> {
        GetTagList {
            actor: self._fields.0,
        }
    }
}