[package]
name = "jacquard"
description.workspace = true
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
documentation.workspace = true
exclude.workspace = true

[features]
default = ["api_all"]
derive = ["dep:jacquard-derive"]
api = ["jacquard-api/com_atproto"]
api_all = ["api", "jacquard-api/app_bsky", "jacquard-api/chat_bsky", "jacquard-api/tools_ozone"]

[lib]
name = "jacquard"
path = "src/lib.rs"

[[bin]]
name = "jacquard"
path = "src/main.rs"

[dependencies]
bytes.workspace = true
clap.workspace = true
http.workspace = true
jacquard-api = { path = "../jacquard-api" }
jacquard-common = { path = "../jacquard-common" }
jacquard-derive = { path = "../jacquard-derive", optional = true }
miette.workspace = true
reqwest = { workspace = true, features = ["charset", "http2", "json", "system-proxy", "gzip", "rustls-tls"] }
serde.workspace = true
serde_html_form.workspace = true
serde_ipld_dagcbor.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
