[package]
authors.workspace = true
# If you change the name here, you must also do it in flake.nix (and run `cargo generate-lockfile` afterwards)
name = "jacquard"
description = "A simple Rust project using Nix"
version.workspace = true
edition.workspace = true

[features]
default = ["api_all"]
derive = ["dep:jacquard-derive"]
api = ["jacquard-api/com_atproto"]
api_all = ["api", "jacquard-api/app_bsky", "jacquard-api/chat_bsky", "jacquard-api/tools_ozone"]

[lib]
name = "jacquard"
path = "src/lib.rs"

[[bin]]
name = "jacquard"
path = "src/main.rs"

[dependencies]
bytes = "1.10"
clap = { workspace = true }
http = "1.3.1"
jacquard-api = { version = "0.1.0", path = "../jacquard-api" }
jacquard-common = { path = "../jacquard-common" }
jacquard-derive = { path = "../jacquard-derive", optional = true }
miette = "7.6.0"
reqwest = { version = "0.12.23", default-features = false, features = ["charset", "http2", "json", "system-proxy", "gzip", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_html_form = "0.2"
serde_ipld_dagcbor = "0.6.4"
serde_json = "1.0"
thiserror = "2.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
