[package]
name = "jacquard"
description.workspace = true
edition.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
exclude.workspace = true
license.workspace = true

[features]
default = ["api_full", "dns", "fancy", "loopback"]
derive = ["dep:jacquard-derive"]
api = ["jacquard-api/com_atproto", "jacquard-api/com_bad_example" ]
api_bluesky = ["api", "jacquard-api/bluesky" ]
api_full = ["api", "jacquard-api/bluesky", "jacquard-api/other", "jacquard-api/lexicon_community"]
api_all = ["api_full", "jacquard-api/ufos"]
dns = ["jacquard-identity/dns"]
fancy = ["miette/fancy"]
# Propagate loopback to oauth (server + browser helper)
loopback = ["jacquard-oauth/loopback", "jacquard-oauth/browser-open"]

[lib]
name = "jacquard"
path = "src/lib.rs"

[[bin]]
name = "jacquard"
path = "src/main.rs"


[dependencies]
jacquard-api = { version = "0.4", path = "../jacquard-api" }
jacquard-common = { version = "0.4", path = "../jacquard-common", features = ["reqwest-client"] }
jacquard-oauth = { version = "0.4", path = "../jacquard-oauth" }
jacquard-derive = { version = "0.4", path = "../jacquard-derive", optional = true }
jacquard-identity = { version = "0.4", path = "../jacquard-identity" }

bon.workspace = true
async-trait.workspace = true
bytes.workspace = true
clap.workspace = true
http.workspace = true
miette = { workspace = true }
reqwest = { workspace = true, features = ["charset", "http2", "json", "system-proxy", "gzip", "rustls-tls"] }
serde.workspace = true
serde_html_form.workspace = true
serde_ipld_dagcbor.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "fs"] }
url.workspace = true
smol_str.workspace = true
percent-encoding.workspace = true
urlencoding.workspace = true
jose-jwk = { workspace = true, features = ["p256"] }
p256 = { workspace = true, features = ["ecdsa"] }
rand_core.workspace = true

[package.metadata.docs.rs]
features = [ "api_all", "derive", "dns", "fancy", "loopback" ]
