[package]
authors.workspace = true
# If you change the name here, you must also do it in flake.nix (and run `cargo generate-lockfile` afterwards)
name = "jacquard"
description = "A simple Rust project using Nix"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
jacquard-api = { version = "0.1.0", path = "../jacquard-api" }
jacquard-common = { path = "../jacquard-common" }
reqwest = { version = "0.12.23", default-features = false, features = ["charset", "http2", "json", "system-proxy", "gzip", "rustls-tls"] }
