[package]
name = "jacquard"
description.workspace = true
edition.workspace = true
version = "0.2.1"
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
exclude.workspace = true
license.workspace = true

[features]
default = ["api_all", "dns", "fancy", "loopback"]
derive = ["dep:jacquard-derive"]
api = ["jacquard-api/com_atproto"]
api_all = ["api", "jacquard-api/app_bsky", "jacquard-api/chat_bsky", "jacquard-api/tools_ozone"]
dns = ["dep:hickory-resolver", "jacquard-common/dns"]
fancy = ["miette/fancy"]
loopback = ["dep:rouille"]

[lib]
name = "jacquard"
path = "src/lib.rs"

[[bin]]
name = "jacquard"
path = "src/main.rs"


[dependencies]
bon = "3"
async-trait = "0.1"
bytes.workspace = true
clap.workspace = true
http.workspace = true
jacquard-api = { version = "0.2.0", path = "../jacquard-api" }
jacquard-common = { version = "0.2.0", path = "../jacquard-common", features = ["reqwest-client"] }
jacquard-oauth = { version = "0.1.0", path = "../jacquard-oauth" }
jacquard-derive = { version = "0.2.0", path = "../jacquard-derive", optional = true }
miette = { workspace = true }
reqwest = { workspace = true, features = ["charset", "http2", "json", "system-proxy", "gzip", "rustls-tls"] }
serde.workspace = true
serde_html_form.workspace = true
serde_ipld_dagcbor.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { version = "1", features = ["macros", "rt-multi-thread", "fs"] }
hickory-resolver = { version = "0.24", default-features = false, features = ["system-config", "tokio-runtime"], optional = true }
url.workspace = true
smol_str.workspace = true
percent-encoding = "2"
urlencoding = "2"
jose-jwk = { version = "0.1", features = ["p256"] }
p256 = { version = "0.13", features = ["ecdsa"] }
rand_core = "0.6"
rouille = { version = "3.6.2", optional = true }
