[package]
authors.workspace = true
# If you change the name here, you must also do it in flake.nix (and run `cargo generate-lockfile` afterwards)
name = "jacquard"
description = "A simple Rust project using Nix"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
jacquard-common = { path = "../jacquard-common" }
