// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: fm.teal.alpha.stats.getLatest
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_derive::{IntoStatic, lexicon};
use serde::{Serialize, Deserialize};
use crate::fm_teal::alpha::feed::PlayView;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct GetLatest {
    ///Defaults to `50`. Min: 1. Max: 100.
    #[serde(default = "_default_limit")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
}


#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct GetLatestOutput<'a> {
    #[serde(borrow)]
    pub plays: Vec<PlayView<'a>>,
}

/// Response type for fm.teal.alpha.stats.getLatest
pub struct GetLatestResponse;
impl jacquard_common::xrpc::XrpcResp for GetLatestResponse {
    const NSID: &'static str = "fm.teal.alpha.stats.getLatest";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = GetLatestOutput<'de>;
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl jacquard_common::xrpc::XrpcRequest for GetLatest {
    const NSID: &'static str = "fm.teal.alpha.stats.getLatest";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetLatestResponse;
}

/// Endpoint type for fm.teal.alpha.stats.getLatest
pub struct GetLatestRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetLatestRequest {
    const PATH: &'static str = "/xrpc/fm.teal.alpha.stats.getLatest";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = GetLatest;
    type Response = GetLatestResponse;
}

fn _default_limit() -> Option<i64> {
    Some(50i64)
}

pub mod get_latest_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {}
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {}
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {}
}

/// Builder for constructing an instance of this type
pub struct GetLatestBuilder<S: get_latest_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<i64>,),
}

impl GetLatest {
    /// Create a new builder for this type
    pub fn new() -> GetLatestBuilder<get_latest_state::Empty> {
        GetLatestBuilder::new()
    }
}

impl GetLatestBuilder<get_latest_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        GetLatestBuilder {
            _state: PhantomData,
            _fields: (None,),
        }
    }
}

impl<S: get_latest_state::State> GetLatestBuilder<S> {
    /// Set the `limit` field (optional)
    pub fn limit(mut self, value: impl Into<Option<i64>>) -> Self {
        self._fields.0 = value.into();
        self
    }
    /// Set the `limit` field to an Option value (optional)
    pub fn maybe_limit(mut self, value: Option<i64>) -> Self {
        self._fields.0 = value;
        self
    }
}

impl<S> GetLatestBuilder<S>
where
    S: get_latest_state::State,
{
    /// Build the final struct
    pub fn build(self) -> GetLatest {
        GetLatest { limit: self._fields.0 }
    }
}