// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: app.chronosky.media.getBlob
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, Bos, DefaultStr};
use jacquard_common::deps::bytes::Bytes;
use jacquard_derive::{IntoStatic, open_union};
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
#[serde(
    bound(
        serialize = "S: Serialize + Bos<str> + AsRef<str>",
        deserialize = "S: Deserialize<'de> + Bos<str> + AsRef<str>"
    )
)]
pub struct GetBlob<S: Bos<str> + AsRef<str> = DefaultStr> {
    #[serde(borrow)]
    pub cid: S,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct GetBlobOutput {
    pub body: Bytes,
}


#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic
)]

#[serde(tag = "error", content = "message")]
pub enum GetBlobError {
    /// The requested blob was not found.
    #[serde(rename = "BlobNotFound")]
    BlobNotFound(Option<jacquard_common::deps::smol_str::SmolStr>),
    /// Invalid CID format or missing parameters.
    #[serde(rename = "InvalidRequest")]
    InvalidRequest(Option<jacquard_common::deps::smol_str::SmolStr>),
    /// Catch-all for unknown error codes.
    #[serde(untagged)]
    Other {
        error: jacquard_common::deps::smol_str::SmolStr,
        message: Option<jacquard_common::deps::smol_str::SmolStr>,
    },
}

impl core::fmt::Display for GetBlobError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::BlobNotFound(msg) => {
                write!(f, "BlobNotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::InvalidRequest(msg) => {
                write!(f, "InvalidRequest")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Other { error, message } => {
                write!(f, "{}", error)?;
                if let Some(msg) = message {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
        }
    }
}

/// Response type for app.chronosky.media.getBlob
pub struct GetBlobResponse;
impl jacquard_common::xrpc::XrpcResp for GetBlobResponse {
    const NSID: &'static str = "app.chronosky.media.getBlob";
    const ENCODING: &'static str = "*/*";
    type Output<S: Bos<str> + AsRef<str>> = GetBlobOutput;
    type Err = GetBlobError;
    fn encode_output<S: Bos<str> + AsRef<str>>(
        output: &Self::Output<S>,
    ) -> Result<Vec<u8>, jacquard_common::xrpc::EncodeError>
    where
        Self::Output<S>: Serialize,
    {
        Ok(output.body.to_vec())
    }
    fn decode_output<'de, S>(
        body: &'de [u8],
    ) -> Result<Self::Output<S>, jacquard_common::error::DecodeError>
    where
        S: Bos<str> + AsRef<str> + Deserialize<'de>,
        Self::Output<S>: Deserialize<'de>,
    {
        Ok(GetBlobOutput {
            body: jacquard_common::deps::bytes::Bytes::copy_from_slice(body),
        })
    }
}

impl<S: Bos<str> + AsRef<str> + Serialize> jacquard_common::xrpc::XrpcRequest
for GetBlob<S> {
    const NSID: &'static str = "app.chronosky.media.getBlob";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetBlobResponse;
}

/// Endpoint type for app.chronosky.media.getBlob
pub struct GetBlobRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetBlobRequest {
    const PATH: &'static str = "/xrpc/app.chronosky.media.getBlob";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: Bos<str> + AsRef<str>> = GetBlob<S>;
    type Response = GetBlobResponse;
}

pub mod get_blob_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Cid;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Cid = Unset;
    }
    ///State transition - sets the `cid` field to Set
    pub struct SetCid<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCid<S> {}
    impl<S: State> State for SetCid<S> {
        type Cid = Set<members::cid>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `cid` field
        pub struct cid(());
    }
}

/// Builder for constructing an instance of this type
pub struct GetBlobBuilder<'a, S: get_blob_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<S>,),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> GetBlob<'a> {
    /// Create a new builder for this type
    pub fn new() -> GetBlobBuilder<'a, get_blob_state::Empty> {
        GetBlobBuilder::new()
    }
}

impl<'a> GetBlobBuilder<'a, get_blob_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        GetBlobBuilder {
            _state: PhantomData,
            _fields: (None,),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> GetBlobBuilder<'a, S>
where
    S: get_blob_state::State,
    S::Cid: get_blob_state::IsUnset,
{
    /// Set the `cid` field (required)
    pub fn cid(
        mut self,
        value: impl Into<S>,
    ) -> GetBlobBuilder<'a, get_blob_state::SetCid<S>> {
        self._fields.0 = Option::Some(value.into());
        GetBlobBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> GetBlobBuilder<'a, S>
where
    S: get_blob_state::State,
    S::Cid: get_blob_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> GetBlob<'a> {
        GetBlob {
            cid: self._fields.0.unwrap(),
        }
    }
}